"use client";

import { useState } from "react";
import { ConfirmDialog } from "@/components/common/confirm-dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { closeEvacuationAction, createEvacuationAction, createGatePassAction, createSecurityIncidentAction, createVisitorAction, transitionGatePassAction, transitionSecurityIncidentAction } from "../actions/safety.actions";

type Visitor = { id: string; name: string };
function Message({ value }: { value: string }) { return value ? <p role="status" className="text-sm text-muted-foreground">{value}</p> : null; }

export function VisitorForm() { const [message, setMessage] = useState(""); async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); const result = await createVisitorAction({ visitorName: data.get("visitorName"), purpose: data.get("purpose"), hostName: data.get("hostName"), visitAt: data.get("visitAt") }); setMessage(result.ok ? result.message ?? "Registered." : result.error); if (result.ok) event.currentTarget.reset(); } return <form onSubmit={submit} className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4" noValidate><div className="space-y-2"><Label htmlFor="visitor-name">Visitor name</Label><Input id="visitor-name" name="visitorName" required /></div><div className="space-y-2"><Label htmlFor="visitor-purpose">Purpose</Label><Input id="visitor-purpose" name="purpose" required /></div><div className="space-y-2"><Label htmlFor="visitor-host">Host</Label><Input id="visitor-host" name="hostName" required /></div><div className="space-y-2"><Label htmlFor="visitor-time">Visit time</Label><Input id="visitor-time" name="visitAt" type="datetime-local" required /></div><div className="sm:col-span-2 lg:col-span-4 flex items-center justify-between gap-3"><Message value={message} /><Button>Register visitor</Button></div></form>; }

export function GatePassForm({ visitors }: { visitors: Visitor[] }) { const [message, setMessage] = useState(""); async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); const result = await createGatePassAction({ visitorId: data.get("visitorId"), reason: data.get("reason"), validUntil: data.get("validUntil") }); setMessage(result.ok ? result.message ?? "Requested." : result.error); if (result.ok) event.currentTarget.reset(); } return <form onSubmit={submit} className="grid gap-4 sm:grid-cols-3" noValidate><div className="space-y-2"><Label htmlFor="gate-visitor">Visitor</Label><select id="gate-visitor" name="visitorId" className="h-10 w-full rounded-md border bg-background px-3 text-sm" required><option value="">Choose visitor</option>{visitors.map((visitor) => <option key={visitor.id} value={visitor.id}>{visitor.name}</option>)}</select></div><div className="space-y-2"><Label htmlFor="gate-reason">Reason</Label><Input id="gate-reason" name="reason" required /></div><div className="space-y-2"><Label htmlFor="gate-expiry">Valid until</Label><Input id="gate-expiry" name="validUntil" type="datetime-local" required /></div><div className="sm:col-span-3 flex items-center justify-between gap-3"><Message value={message} /><Button disabled={!visitors.length}>Request gate pass</Button></div></form>; }

export function GatePassButton({ id, toStatus }: { id: string; toStatus: "approved" | "rejected" | "used" | "expired" | "cancelled" }) { const [message, setMessage] = useState(""); async function submit() { const result = await transitionGatePassAction({ id, toStatus }); if (!result.ok) { setMessage(result.error); throw new Error(result.error); } setMessage(result.message ?? "Updated."); window.location.reload(); } return <div className="flex items-center gap-2"><ConfirmDialog label={toStatus} title={`Mark gate pass ${toStatus}?`} description="The gate-pass status will be changed and the update will remain in the safety history." triggerVariant="outline" confirmVariant={toStatus === "rejected" || toStatus === "cancelled" || toStatus === "expired" ? "destructive" : "default"} onConfirm={submit} /><Message value={message} /></div>; }

export function SecurityIncidentForm() { const [message, setMessage] = useState(""); async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); const result = await createSecurityIncidentAction({ title: data.get("title"), severity: data.get("severity"), occurredAt: data.get("occurredAt"), details: data.get("details") }); setMessage(result.ok ? result.message ?? "Recorded." : result.error); if (result.ok) event.currentTarget.reset(); } return <form onSubmit={submit} className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4" noValidate><div className="space-y-2"><Label htmlFor="incident-title">Title</Label><Input id="incident-title" name="title" required /></div><div className="space-y-2"><Label htmlFor="incident-severity">Severity</Label><select id="incident-severity" name="severity" className="h-10 w-full rounded-md border bg-background px-3 text-sm"><option>low</option><option>medium</option><option>high</option><option>critical</option></select></div><div className="space-y-2"><Label htmlFor="incident-time">Occurred at</Label><Input id="incident-time" name="occurredAt" type="datetime-local" required /></div><div className="space-y-2"><Label htmlFor="incident-details">Details</Label><Input id="incident-details" name="details" required /></div><div className="sm:col-span-2 lg:col-span-4 flex items-center justify-between gap-3"><Message value={message} /><Button>Record incident</Button></div></form>; }

export function SecurityIncidentButton({ id, toStatus }: { id: string; toStatus: "investigating" | "resolved" | "closed" }) { const [message, setMessage] = useState(""); async function submit() { const result = await transitionSecurityIncidentAction({ id, toStatus }); if (!result.ok) { setMessage(result.error); throw new Error(result.error); } setMessage(result.message ?? "Updated."); window.location.reload(); } return <div className="flex items-center gap-2"><ConfirmDialog label={toStatus} title={`Mark incident ${toStatus}?`} description="The incident status and its audit history will be updated. Confirm the resolution or closure before continuing." triggerVariant="outline" confirmVariant={toStatus === "closed" ? "destructive" : "default"} onConfirm={submit} /><Message value={message} /></div>; }

export function EvacuationForm() { const [message, setMessage] = useState(""); async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); const result = await createEvacuationAction({ title: data.get("title"), startedAt: data.get("startedAt"), notes: data.get("notes") }); setMessage(result.ok ? result.message ?? "Opened." : result.error); if (result.ok) event.currentTarget.reset(); } return <form onSubmit={submit} className="grid gap-4 sm:grid-cols-3" noValidate><div className="space-y-2"><Label htmlFor="evacuation-title">Exercise / event</Label><Input id="evacuation-title" name="title" required /></div><div className="space-y-2"><Label htmlFor="evacuation-start">Started at</Label><Input id="evacuation-start" name="startedAt" type="datetime-local" required /></div><div className="space-y-2"><Label htmlFor="evacuation-notes">Notes</Label><Input id="evacuation-notes" name="notes" /></div><div className="sm:col-span-3 flex items-center justify-between gap-3"><Message value={message} /><Button>Open roll call</Button></div></form>; }

export function EvacuationCloseButton({ id }: { id: string }) { const [message, setMessage] = useState(""); async function submit() { const result = await closeEvacuationAction({ id, toStatus: "closed" }); if (!result.ok) { setMessage(result.error); throw new Error(result.error); } setMessage(result.message ?? "Closed."); window.location.reload(); } return <div className="flex items-center gap-2"><ConfirmDialog label="Close" title="Close this evacuation roll call?" description="The roll call will be closed and no further attendance updates will be accepted for this event." triggerVariant="outline" onConfirm={submit} /><Message value={message} /></div>; }
