"use client";
import Link from "next/link";
import { useState } from "react";
import { createUserWithEmailAndPassword, sendEmailVerification, updateProfile } from "firebase/auth";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { getFirebaseAuth } from "@/lib/auth/firebase-client";
export function RegisterForm() { const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [name, setName] = useState(""); const [error, setError] = useState(""); const [message, setMessage] = useState(""); const [pending, setPending] = useState(false); async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setPending(true); setError(""); try { const credential = await createUserWithEmailAndPassword(getFirebaseAuth(), email, password); await updateProfile(credential.user, { displayName: name }); await sendEmailVerification(credential.user); setMessage("Account created. Check your email, then ask an administrator to provision your school role."); } catch (caught) { setError(caught instanceof Error ? caught.message : "Registration failed."); } finally { setPending(false); } } return <form onSubmit={submit} className="space-y-4"><div className="space-y-2"><Label htmlFor="name">Full name</Label><Input id="name" required value={name} onChange={(event) => setName(event.target.value)} /></div><div className="space-y-2"><Label htmlFor="email">Work email</Label><Input id="email" type="email" required value={email} onChange={(event) => setEmail(event.target.value)} /></div><div className="space-y-2"><Label htmlFor="password">Password</Label><Input id="password" type="password" minLength={8} required value={password} onChange={(event) => setPassword(event.target.value)} /></div>{error ? <p className="text-sm text-red-600">{error}</p> : null}{message ? <p className="text-sm text-emerald-600">{message}</p> : null}<Button className="w-full" disabled={pending}>{pending ? "Creating…" : "Create account"}</Button><p className="text-center text-sm text-muted-foreground">Already registered? <Link href="/login" className="text-primary">Sign in</Link></p></form>; }
