"use server";

import { revalidatePath } from "next/cache";
import { requirePermission } from "@/lib/auth/guards";
import { writeAuditLog } from "@/lib/audit/audit-log";
import type { ActionResult } from "@/lib/errors/result";
import { facilityBookingSchema, facilityBookingStatusSchema, facilityComplaintSchema, facilityComplaintStatusSchema, facilityMaintenanceSchema, facilityMaintenanceStatusSchema } from "../schemas/facilities.schema";
import { createFacilityBooking, createFacilityComplaint, createFacilityMaintenance, transitionFacilityBooking, transitionFacilityComplaint, transitionFacilityMaintenance } from "../services/facilities.service";

function invalid(message: string): ActionResult<{ id: string }> { return { ok: false, error: message, code: "VALIDATION_ERROR" }; }
export async function createFacilityBookingAction(input: unknown): Promise<ActionResult<{ id: string }>> { const parsed = facilityBookingSchema.safeParse(input); if (!parsed.success) return invalid(parsed.error.issues[0]?.message ?? "Booking details are invalid."); try { const user = await requirePermission("facilities:create"); const row = await createFacilityBooking(user, parsed.data); await writeAuditLog(user, { action: "create", module: "facilities", entityType: "facility_booking", entityId: row.id, campusId: row.campusId, after: { status: row.status } }); revalidatePath("/facilities/bookings"); return { ok: true, data: { id: row.id }, message: "Facility booking requested." }; } catch (error) { return { ok: false, error: error instanceof Error ? error.message : "Unable to request booking." }; } }
export async function transitionFacilityBookingAction(input: unknown): Promise<ActionResult<{ id: string }>> { const parsed = facilityBookingStatusSchema.safeParse(input); if (!parsed.success) return invalid(parsed.error.issues[0]?.message ?? "Booking status is invalid."); try { const user = await requirePermission("facilities:approve"); const row = await transitionFacilityBooking(user, parsed.data); await writeAuditLog(user, { action: "update", module: "facilities", entityType: "facility_booking", entityId: row.id, campusId: row.campusId, after: { status: row.status } }); revalidatePath("/facilities/bookings"); return { ok: true, data: { id: row.id }, message: `Booking moved to ${row.status}.` }; } catch (error) { return { ok: false, error: error instanceof Error ? error.message : "Unable to update booking." }; } }
export async function createFacilityMaintenanceAction(input: unknown): Promise<ActionResult<{ id: string }>> { const parsed = facilityMaintenanceSchema.safeParse(input); if (!parsed.success) return invalid(parsed.error.issues[0]?.message ?? "Maintenance details are invalid."); try { const user = await requirePermission("facilities:create"); const row = await createFacilityMaintenance(user, parsed.data); await writeAuditLog(user, { action: "create", module: "facilities", entityType: "facility_maintenance", entityId: row.id, campusId: row.campusId, after: { status: row.status } }); revalidatePath("/facilities/maintenance"); return { ok: true, data: { id: row.id }, message: "Maintenance ticket created." }; } catch (error) { return { ok: false, error: error instanceof Error ? error.message : "Unable to create maintenance ticket." }; } }
export async function transitionFacilityMaintenanceAction(input: unknown): Promise<ActionResult<{ id: string }>> { const parsed = facilityMaintenanceStatusSchema.safeParse(input); if (!parsed.success) return invalid(parsed.error.issues[0]?.message ?? "Maintenance status is invalid."); try { const user = await requirePermission("facilities:update"); const row = await transitionFacilityMaintenance(user, parsed.data); await writeAuditLog(user, { action: "update", module: "facilities", entityType: "facility_maintenance", entityId: row.id, campusId: row.campusId, after: { status: row.status } }); revalidatePath("/facilities/maintenance"); return { ok: true, data: { id: row.id }, message: `Maintenance ticket moved to ${row.status}.` }; } catch (error) { return { ok: false, error: error instanceof Error ? error.message : "Unable to update maintenance ticket." }; } }
export async function createFacilityComplaintAction(input: unknown): Promise<ActionResult<{ id: string }>> { const parsed = facilityComplaintSchema.safeParse(input); if (!parsed.success) return invalid(parsed.error.issues[0]?.message ?? "Complaint details are invalid."); try { const user = await requirePermission("facilities:create"); const row = await createFacilityComplaint(user, parsed.data); await writeAuditLog(user, { action: "create", module: "facilities", entityType: "facility_complaint", entityId: row.id, campusId: row.campusId, after: { status: row.status } }); revalidatePath("/facilities/complaints"); return { ok: true, data: { id: row.id }, message: "Complaint submitted." }; } catch (error) { return { ok: false, error: error instanceof Error ? error.message : "Unable to submit complaint." }; } }
export async function transitionFacilityComplaintAction(input: unknown): Promise<ActionResult<{ id: string }>> { const parsed = facilityComplaintStatusSchema.safeParse(input); if (!parsed.success) return invalid(parsed.error.issues[0]?.message ?? "Complaint status is invalid."); try { const user = await requirePermission("facilities:update"); const row = await transitionFacilityComplaint(user, parsed.data); await writeAuditLog(user, { action: "update", module: "facilities", entityType: "facility_complaint", entityId: row.id, campusId: row.campusId, after: { status: row.status } }); revalidatePath("/facilities/complaints"); return { ok: true, data: { id: row.id }, message: `Complaint moved to ${row.status}.` }; } catch (error) { return { ok: false, error: error instanceof Error ? error.message : "Unable to update complaint." }; } }
