import { PageHeader } from "@/components/common/page-header";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { FacilityMaintenanceButton, FacilityMaintenanceForm } from "@/features/facilities/components/facilities-workspace";
import { listFacilityMaintenance } from "@/lib/api-client/server-queries";
import { requirePermission } from "@/lib/auth/guards";
import { hasPermission } from "@/lib/rbac/permissions";

function details(value: string | null) { try { return value ? JSON.parse(value) as { facilityName?: string; priority?: string } : {}; } catch { return {}; } }
export default async function FacilitiesMaintenancePage() { const user = await requirePermission("facilities:read"); const tickets = await listFacilityMaintenance(user); return <div className="space-y-6"><PageHeader title="Facility maintenance" description="Track facility issues from open through resolution with priority and audit history." />{hasPermission(user, "facilities:create") ? <Card><CardHeader><CardTitle>New maintenance ticket</CardTitle></CardHeader><CardContent><FacilityMaintenanceForm /></CardContent></Card> : null}<Card><CardHeader><CardTitle>Maintenance history</CardTitle></CardHeader><CardContent>{tickets.length ? <div className="space-y-3">{tickets.map((ticket) => { const info = details(ticket.detailsJson); return <div key={ticket.id} className="flex flex-wrap items-center justify-between gap-3 rounded-lg border p-4"><div><p className="font-medium">{ticket.name}</p><p className="text-xs text-muted-foreground">{info.facilityName ?? "Facility"} · {info.priority ?? "priority unknown"}</p></div><div className="flex items-center gap-3"><Badge variant={ticket.status === "completed" ? "success" : "secondary"}>{ticket.status}</Badge>{hasPermission(user, "facilities:update") && ticket.status === "open" ? <FacilityMaintenanceButton id={ticket.id} toStatus="in_progress" /> : null}{hasPermission(user, "facilities:update") && ticket.status === "in_progress" ? <FacilityMaintenanceButton id={ticket.id} toStatus="completed" /> : null}</div></div>; })}</div> : <p className="rounded-lg border border-dashed p-8 text-center text-sm text-muted-foreground">No maintenance tickets found.</p>}</CardContent></Card></div>; }
