import { PageHeader } from "@/components/common/page-header";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { SecurityIncidentButton, SecurityIncidentForm } from "@/features/safety/components/safety-workspace";
import { listSecurityIncidents } from "@/lib/api-client/server-queries";
import { requirePermission } from "@/lib/auth/guards";
import { hasPermission } from "@/lib/rbac/permissions";

function details(value: string | null) { try { return value ? JSON.parse(value) as { severity?: string; details?: string } : {}; } catch { return {}; } }
export default async function SafetyIncidentsPage() { const user = await requirePermission("safety:read"); const incidents = await listSecurityIncidents(user); return <div className="space-y-6"><PageHeader title="Security incidents" description="Record, investigate, resolve, and close safety incidents with severity and audit history." />{hasPermission(user, "safety:create") ? <Card><CardHeader><CardTitle>Record incident</CardTitle></CardHeader><CardContent><SecurityIncidentForm /></CardContent></Card> : null}<Card><CardHeader><CardTitle>Incident history</CardTitle></CardHeader><CardContent>{incidents.length ? <div className="space-y-3">{incidents.map((incident) => { const info = details(incident.detailsJson); return <div key={incident.id} className="flex flex-wrap items-center justify-between gap-3 rounded-lg border p-4"><div><p className="font-medium">{incident.name}</p><p className="text-xs text-muted-foreground">{info.severity ?? "severity unknown"} · {incident.effectiveAt ? new Date(incident.effectiveAt).toLocaleString() : "unknown"}</p></div><div className="flex items-center gap-3"><Badge variant={info.severity === "critical" || info.severity === "high" ? "warning" : "secondary"}>{incident.status}</Badge>{hasPermission(user, "safety:update") && incident.status === "open" ? <SecurityIncidentButton id={incident.id} toStatus="investigating" /> : null}{hasPermission(user, "safety:update") && incident.status === "investigating" ? <SecurityIncidentButton id={incident.id} toStatus="resolved" /> : null}{hasPermission(user, "safety:update") && incident.status === "resolved" ? <SecurityIncidentButton id={incident.id} toStatus="closed" /> : null}</div></div>; })}</div> : <p className="rounded-lg border border-dashed p-8 text-center text-sm text-muted-foreground">No incidents found.</p>}</CardContent></Card></div>; }
