import { errorEnvelopeSchema } from "../schemas";

const meta = { type: "object", required: ["requestId"], properties: { requestId: { type: "string" } } } as const;
const row = { type: "object", required: ["id", "name", "detail", "status"], properties: { id: { type: "string" }, name: { type: "string" }, detail: { type: "string" }, status: { type: "string" } } } as const;
const securedErrors = { 401: errorEnvelopeSchema, 403: errorEnvelopeSchema, 404: errorEnvelopeSchema, 422: errorEnvelopeSchema, 503: errorEnvelopeSchema } as const;
const params = { type: "object", additionalProperties: false, required: ["kind"], properties: { kind: { type: "string", enum: ["curriculum", "lesson-plans", "teacher-allocation", "timetable", "substitutions", "assignments", "resources"] } } } as const;
const body = { type: "object", additionalProperties: false, required: ["name"], properties: { name: { type: "string", minLength: 2, maxLength: 160 }, code: { type: "string", maxLength: 80 }, referenceId: { type: "string", maxLength: 120 }, teacherId: { type: "string", maxLength: 120 }, classId: { type: "string", maxLength: 120 }, subjectId: { type: "string", maxLength: 120 }, scheduledFor: { type: "string", format: "date-time" }, dueAt: { type: "string", format: "date-time" }, details: { type: "string", maxLength: 2_000 } } } as const;
export const academicListSchema = { tags: ["academics"], summary: "List scoped academic records", security: [{ firebaseBearer: [] }], params, querystring: { type: "object", additionalProperties: false, properties: { search: { type: "string", maxLength: 160 } } }, response: { 200: { type: "object", required: ["data", "meta"], properties: { data: { type: "array", items: row }, meta } }, ...securedErrors } } as const;
export const academicCreateSchema = { tags: ["academics"], summary: "Create a scoped academic record", security: [{ firebaseBearer: [] }], params, body, response: { 201: { type: "object", required: ["data", "meta"], properties: { data: { type: "object", required: ["id"], properties: { id: { type: "string" } } }, meta } }, ...securedErrors } } as const;
export const academicArchiveSchema = { tags: ["academics"], summary: "Archive a scoped academic record", security: [{ firebaseBearer: [] }], params: { type: "object", additionalProperties: false, required: ["kind", "id"], properties: { ...params.properties, id: { type: "string", minLength: 1, maxLength: 120 } } }, response: { 200: { type: "object", required: ["data", "meta"], properties: { data: { type: "object", required: ["id"], properties: { id: { type: "string" } } }, meta } }, ...securedErrors } } as const;
