import { index, integer, sqliteTable, text, uniqueIndex } from "drizzle-orm/sqlite-core";
import { auditColumns, idColumn, tenantColumns, statusColumn } from "./shared";

export const examTypes = sqliteTable("exam_types", { id: idColumn("exam_type"), ...tenantColumns(), name: text("name").notNull(), code: text("code").notNull(), ...auditColumns(), status: statusColumn() }, (table) => [uniqueIndex("exam_types_org_code_unique").on(table.organizationId, table.code)]);
export const examSchemes = sqliteTable("exam_schemes", { id: idColumn("exam_scheme"), ...tenantColumns(), academicYearId: text("academic_year_id").notNull(), name: text("name").notNull(), weightage: integer("weightage").notNull().default(100), configurationJson: text("configuration_json"), ...auditColumns(), status: statusColumn("draft") }, (table) => [index("exam_schemes_year_idx").on(table.organizationId, table.academicYearId)]);
export const exams = sqliteTable("exams", { id: idColumn("exam"), ...tenantColumns(), academicYearId: text("academic_year_id").notNull(), examSchemeId: text("exam_scheme_id"), name: text("name").notNull(), maxMarks: integer("max_marks").notNull(), startsOn: integer("starts_on", { mode: "timestamp" }), endsOn: integer("ends_on", { mode: "timestamp" }), ...auditColumns(), status: statusColumn("draft") }, (table) => [index("exams_org_idx").on(table.organizationId, table.academicYearId)]);
export const examSchedules = sqliteTable("exam_schedules", { id: idColumn("exam_schedule"), ...tenantColumns(), examId: text("exam_id").notNull(), subjectId: text("subject_id").notNull(), classId: text("class_id").notNull(), startsAt: integer("starts_at", { mode: "timestamp" }).notNull(), endsAt: integer("ends_at", { mode: "timestamp" }).notNull(), roomId: text("room_id"), ...auditColumns(), status: statusColumn() }, (table) => [index("exam_schedules_exam_idx").on(table.organizationId, table.examId, table.startsAt)]);
export const marksEntries = sqliteTable("marks_entries", { id: idColumn("mark"), ...tenantColumns(), examId: text("exam_id").notNull(), studentId: text("student_id").notNull(), subjectId: text("subject_id").notNull(), marks: integer("marks"), state: text("state").notNull().default("entered"), enteredBy: text("entered_by").notNull(), ...auditColumns(), status: statusColumn() }, (table) => [uniqueIndex("marks_exam_student_subject_unique").on(table.examId, table.studentId, table.subjectId), index("marks_exam_idx").on(table.organizationId, table.examId)]);
export const resultPublications = sqliteTable("result_publications", { id: idColumn("publication"), ...tenantColumns(), examId: text("exam_id").notNull(), publishedAt: integer("published_at", { mode: "timestamp" }), publishedBy: text("published_by"), ...auditColumns(), status: statusColumn("draft") }, (table) => [uniqueIndex("result_publication_exam_unique").on(table.examId)]);
export const gradeRules = sqliteTable("grade_rules", { id: idColumn("grade_rule"), ...tenantColumns(), examSchemeId: text("exam_scheme_id").notNull(), grade: text("grade").notNull(), minimumPercent: integer("minimum_percent").notNull(), maximumPercent: integer("maximum_percent").notNull(), gradePoint: integer("grade_point"), ...auditColumns(), status: statusColumn() }, (table) => [index("grade_rules_scheme_idx").on(table.organizationId, table.examSchemeId)]);
export const reportCards = sqliteTable("report_cards", { id: idColumn("report_card"), ...tenantColumns(), examId: text("exam_id").notNull(), studentId: text("student_id").notNull(), summaryJson: text("summary_json").notNull(), generatedAt: integer("generated_at", { mode: "timestamp" }).notNull(), ...auditColumns(), status: statusColumn("generated") }, (table) => [uniqueIndex("report_cards_exam_student_unique").on(table.examId, table.studentId)]);
export const questionBankItems = sqliteTable("question_bank_items", { id: idColumn("question"), ...tenantColumns(), subjectId: text("subject_id").notNull(), questionType: text("question_type").notNull(), prompt: text("prompt").notNull(), answerJson: text("answer_json"), maximumMarks: integer("maximum_marks").notNull(), ...auditColumns(), status: statusColumn("draft") }, (table) => [index("question_bank_subject_idx").on(table.organizationId, table.subjectId, table.questionType)]);
