import { index, integer, sqliteTable, text, uniqueIndex } from "drizzle-orm/sqlite-core";
import { auditColumns, idColumn, tenantColumns, statusColumn } from "./shared";

export const notices = sqliteTable("notices", { id: idColumn("notice"), ...tenantColumns(), title: text("title").notNull(), body: text("body").notNull(), audience: text("audience").notNull(), publishedAt: integer("published_at", { mode: "timestamp" }), ...auditColumns(), status: statusColumn("draft") }, (table) => [index("notices_org_status_idx").on(table.organizationId, table.status)]);
export const libraryItems = sqliteTable("library_items", { id: idColumn("library_item"), ...tenantColumns(), title: text("title").notNull(), author: text("author"), isbn: text("isbn"), totalCopies: integer("total_copies").notNull().default(0), availableCopies: integer("available_copies").notNull().default(0), ...auditColumns(), status: statusColumn() }, (table) => [index("library_org_idx").on(table.organizationId)]);
export const transportRoutes = sqliteTable("transport_routes", { id: idColumn("route"), ...tenantColumns(), name: text("name").notNull(), vehicleId: text("vehicle_id"), capacity: integer("capacity").notNull().default(0), ...auditColumns(), status: statusColumn() }, (table) => [index("routes_org_idx").on(table.organizationId)]);
export const vehicles = sqliteTable("vehicles", { id: idColumn("vehicle"), ...tenantColumns(), registrationNumber: text("registration_number").notNull(), type: text("type").notNull(), capacity: integer("capacity").notNull(), ...auditColumns(), status: statusColumn() }, (table) => [uniqueIndex("vehicles_org_reg_unique").on(table.organizationId, table.registrationNumber)]);
export const inventoryItems = sqliteTable("inventory_items", { id: idColumn("inventory"), ...tenantColumns(), name: text("name").notNull(), sku: text("sku").notNull(), quantity: integer("quantity").notNull().default(0), reorderLevel: integer("reorder_level").notNull().default(0), ...auditColumns(), status: statusColumn() }, (table) => [uniqueIndex("inventory_org_sku_unique").on(table.organizationId, table.sku)]);
export const integrationLogs = sqliteTable("integration_logs", { id: idColumn("integration_log"), ...tenantColumns(), provider: text("provider").notNull(), eventType: text("event_type").notNull(), payloadJson: text("payload_json"), error: text("error"), ...auditColumns(), status: statusColumn("received") }, (table) => [index("integration_logs_org_idx").on(table.organizationId, table.createdAt)]);
