"use client";

import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { createAchievementAction, createAlumniEventAction, createAlumniProfileAction, createClubAction, createCmsFormAction, createCmsMediaAction, createCmsPageAction, createJobBoardPostAction, createMentorshipAction, transitionCmsFormAction, transitionCmsMediaAction, transitionCmsPageAction } from "../actions/community.actions";

type StudentOption = { id: string; name: string; detail?: string };
function Message({ value }: { value: string }) { return value ? <p role="status" className="text-sm text-muted-foreground">{value}</p> : null; }

export function ClubForm() { const [message, setMessage] = useState(""); async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); const result = await createClubAction({ name: data.get("name"), coordinatorUserId: data.get("coordinatorUserId") }); setMessage(result.ok ? result.message ?? "Created." : result.error); if (result.ok) event.currentTarget.reset(); } return <form onSubmit={submit} className="grid gap-4 sm:grid-cols-2" noValidate><div className="space-y-2"><Label htmlFor="club-name">Club name</Label><Input id="club-name" name="name" required /></div><div className="space-y-2"><Label htmlFor="club-coordinator">Coordinator user ID</Label><Input id="club-coordinator" name="coordinatorUserId" placeholder="Optional" /></div><div className="sm:col-span-2 flex items-center justify-between gap-3"><Message value={message} /><Button>Create club</Button></div></form>; }

export function AchievementForm({ students }: { students: StudentOption[] }) { const [message, setMessage] = useState(""); async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); const result = await createAchievementAction({ studentId: data.get("studentId"), title: data.get("title"), achievedOn: data.get("achievedOn") }); setMessage(result.ok ? result.message ?? "Recorded." : result.error); if (result.ok) event.currentTarget.reset(); } return <form onSubmit={submit} className="grid gap-4 sm:grid-cols-3" noValidate><div className="space-y-2"><Label htmlFor="achievement-student">Student</Label><select id="achievement-student" name="studentId" className="h-10 w-full rounded-md border bg-background px-3 text-sm" required><option value="">Choose a student</option>{students.map((student) => <option key={student.id} value={student.id}>{student.name} · {student.detail ?? student.id}</option>)}</select></div><div className="space-y-2"><Label htmlFor="achievement-title">Achievement</Label><Input id="achievement-title" name="title" required /></div><div className="space-y-2"><Label htmlFor="achievement-date">Achieved on</Label><Input id="achievement-date" name="achievedOn" type="date" required /></div><div className="sm:col-span-3 flex items-center justify-between gap-3"><Message value={message} /><Button disabled={!students.length}>Record achievement</Button></div></form>; }

export function AlumniProfileForm({ students }: { students: StudentOption[] }) { const [message, setMessage] = useState(""); async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); const result = await createAlumniProfileAction({ name: data.get("name"), studentId: data.get("studentId"), graduationYear: data.get("graduationYear"), directoryVisible: data.get("directoryVisible") === "on" }); setMessage(result.ok ? result.message ?? "Created." : result.error); if (result.ok) event.currentTarget.reset(); } return <form onSubmit={submit} className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4" noValidate><div className="space-y-2"><Label htmlFor="alumni-name">Alumni name</Label><Input id="alumni-name" name="name" required /></div><div className="space-y-2"><Label htmlFor="alumni-student">Linked student ID</Label><select id="alumni-student" name="studentId" className="h-10 w-full rounded-md border bg-background px-3 text-sm"><option value="">Unlinked profile</option>{students.map((student) => <option key={student.id} value={student.id}>{student.name} · {student.detail ?? student.id}</option>)}</select></div><div className="space-y-2"><Label htmlFor="alumni-year">Graduation year</Label><Input id="alumni-year" name="graduationYear" inputMode="numeric" maxLength={4} required /></div><label className="flex items-center gap-2 pt-8 text-sm"><input type="checkbox" name="directoryVisible" /> Public alumni directory</label><div className="sm:col-span-2 lg:col-span-4 flex items-center justify-between gap-3"><Message value={message} /><Button>Create alumni profile</Button></div></form>; }

export function AlumniEventForm() { const [message, setMessage] = useState(""); async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); const result = await createAlumniEventAction({ name: data.get("name"), startsAt: data.get("startsAt"), details: data.get("details") }); setMessage(result.ok ? result.message ?? "Created." : result.error); if (result.ok) event.currentTarget.reset(); } return <form onSubmit={submit} className="grid gap-4 sm:grid-cols-3" noValidate><div className="space-y-2"><Label htmlFor="alumni-event-name">Event name</Label><Input id="alumni-event-name" name="name" required /></div><div className="space-y-2"><Label htmlFor="alumni-event-start">Starts at</Label><Input id="alumni-event-start" name="startsAt" type="datetime-local" required /></div><div className="space-y-2"><Label htmlFor="alumni-event-details">Details</Label><Input id="alumni-event-details" name="details" required /></div><div className="sm:col-span-3 flex items-center justify-between gap-3"><Message value={message} /><Button>Create event</Button></div></form>; }

export function MentorshipForm() { const [message, setMessage] = useState(""); async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); const result = await createMentorshipAction({ mentorName: data.get("mentorName"), menteeName: data.get("menteeName"), details: data.get("details") }); setMessage(result.ok ? result.message ?? "Created." : result.error); if (result.ok) event.currentTarget.reset(); } return <form onSubmit={submit} className="grid gap-4 sm:grid-cols-3" noValidate><div className="space-y-2"><Label htmlFor="mentor-name">Mentor</Label><Input id="mentor-name" name="mentorName" required /></div><div className="space-y-2"><Label htmlFor="mentee-name">Mentee</Label><Input id="mentee-name" name="menteeName" required /></div><div className="space-y-2"><Label htmlFor="mentorship-details">Details</Label><Input id="mentorship-details" name="details" required /></div><div className="sm:col-span-3 flex items-center justify-between gap-3"><Message value={message} /><Button>Create mentorship request</Button></div></form>; }

export function JobBoardPostForm() { const [message, setMessage] = useState(""); async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); const result = await createJobBoardPostAction({ title: data.get("title"), company: data.get("company"), details: data.get("details") }); setMessage(result.ok ? result.message ?? "Saved." : result.error); if (result.ok) event.currentTarget.reset(); } return <form onSubmit={submit} className="grid gap-4 sm:grid-cols-3" noValidate><div className="space-y-2"><Label htmlFor="job-title">Role</Label><Input id="job-title" name="title" required /></div><div className="space-y-2"><Label htmlFor="job-company">Company</Label><Input id="job-company" name="company" required /></div><div className="space-y-2"><Label htmlFor="job-details">Details</Label><Input id="job-details" name="details" required /></div><div className="sm:col-span-3 flex items-center justify-between gap-3"><Message value={message} /><Button>Save job post</Button></div></form>; }

export function CmsPageForm() { const [message, setMessage] = useState(""); async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); const result = await createCmsPageAction({ slug: data.get("slug"), title: data.get("title"), body: data.get("body"), seoTitle: data.get("seoTitle"), seoDescription: data.get("seoDescription") }); setMessage(result.ok ? result.message ?? "Created." : result.error); if (result.ok) event.currentTarget.reset(); } return <form onSubmit={submit} className="space-y-4" noValidate><div className="grid gap-4 sm:grid-cols-2"><div className="space-y-2"><Label htmlFor="cms-slug">Slug</Label><Input id="cms-slug" name="slug" placeholder="about-school" required /></div><div className="space-y-2"><Label htmlFor="cms-title">Title</Label><Input id="cms-title" name="title" required /></div></div><div className="space-y-2"><Label htmlFor="cms-body">Body</Label><Textarea id="cms-body" name="body" required /></div><div className="grid gap-4 sm:grid-cols-2"><div className="space-y-2"><Label htmlFor="cms-seo-title">SEO title</Label><Input id="cms-seo-title" name="seoTitle" /></div><div className="space-y-2"><Label htmlFor="cms-seo-description">SEO description</Label><Input id="cms-seo-description" name="seoDescription" /></div></div><div className="flex items-center justify-between gap-3"><Message value={message} /><Button>Create draft page</Button></div></form>; }

export function CmsMediaForm() { const [message, setMessage] = useState(""); async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); const result = await createCmsMediaAction({ name: data.get("name"), mediaType: data.get("mediaType"), secureUrl: data.get("secureUrl"), publicId: data.get("publicId") }); setMessage(result.ok ? result.message ?? "Registered." : result.error); if (result.ok) event.currentTarget.reset(); } return <form onSubmit={submit} className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4" noValidate><div className="space-y-2"><Label htmlFor="media-name">Name</Label><Input id="media-name" name="name" required /></div><div className="space-y-2"><Label htmlFor="media-type">Type</Label><select id="media-type" name="mediaType" className="h-10 w-full rounded-md border bg-background px-3 text-sm"><option>image</option><option>video</option><option>document</option></select></div><div className="space-y-2"><Label htmlFor="media-url">Secure URL</Label><Input id="media-url" name="secureUrl" type="url" required /></div><div className="space-y-2"><Label htmlFor="media-public-id">Provider public ID</Label><Input id="media-public-id" name="publicId" /></div><div className="sm:col-span-2 lg:col-span-4 flex items-center justify-between gap-3"><Message value={message} /><Button>Register media draft</Button></div></form>; }

export function CmsFormForm() { const [message, setMessage] = useState(""); async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); const result = await createCmsFormAction({ name: data.get("name"), fieldsJson: data.get("fieldsJson") }); setMessage(result.ok ? result.message ?? "Created." : result.error); if (result.ok) event.currentTarget.reset(); } return <form onSubmit={submit} className="space-y-4" noValidate><div className="space-y-2"><Label htmlFor="form-name">Form name</Label><Input id="form-name" name="name" required /></div><div className="space-y-2"><Label htmlFor="form-fields">Fields JSON</Label><Textarea id="form-fields" name="fieldsJson" defaultValue='[{"name":"email","type":"email","required":true}]' required /></div><div className="flex items-center justify-between gap-3"><Message value={message} /><Button>Create form draft</Button></div></form>; }

export function CmsTransitionButton({ kind, id, toStatus }: { kind: "page" | "media" | "form"; id: string; toStatus: string }) { const [message, setMessage] = useState(""); async function submit() { const result = kind === "page" ? await transitionCmsPageAction({ id, toStatus }) : kind === "media" ? await transitionCmsMediaAction({ id, toStatus }) : await transitionCmsFormAction({ id, toStatus }); setMessage(result.ok ? result.message ?? "Updated." : result.error); if (result.ok) window.location.reload(); } return <div className="flex items-center gap-2"><Button size="sm" variant="outline" onClick={submit}>{toStatus}</Button><Message value={message} /></div>; }
