"use client";

import { useState } from "react";
import { ConfirmDialog } from "@/components/common/confirm-dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { assignAssetAction, createAssetAction, createAssetMaintenanceAction, postAssetDepreciationAction, transitionAssetAction, transitionAssetAssignmentAction, transitionAssetMaintenanceAction } from "../actions/asset.actions";

type Asset = { id: string; name: string; code: string | null; detailsJson: string | null; status: string };
type Assignee = { id: string; firstName: string; lastName: string; employeeNumber?: string | null; admissionNumber?: string | null };
function Message({ value }: { value: string }) { return value ? <p role="status" className="text-sm text-muted-foreground">{value}</p> : null; }
function details(value: string | null) { try { return value ? JSON.parse(value) as { category?: string; bookValueMinor?: number; serialNumber?: string | null } : {}; } catch { return {}; } }

export function AssetForm() {
  const [message, setMessage] = useState("");
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); const result = await createAssetAction({ name: data.get("name"), code: data.get("code"), category: data.get("category"), serialNumber: data.get("serialNumber"), acquisitionMinor: data.get("acquisitionMinor"), usefulLifeMonths: data.get("usefulLifeMonths") }); setMessage(result.ok ? result.message ?? "Registered." : result.error); if (result.ok) event.currentTarget.reset(); }
  return <form onSubmit={submit} className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3" noValidate><div className="space-y-2"><Label htmlFor="asset-name">Asset name</Label><Input id="asset-name" name="name" required /></div><div className="space-y-2"><Label htmlFor="asset-code">Asset code</Label><Input id="asset-code" name="code" required /></div><div className="space-y-2"><Label htmlFor="asset-category">Category</Label><Input id="asset-category" name="category" required /></div><div className="space-y-2"><Label htmlFor="asset-serial">Serial number</Label><Input id="asset-serial" name="serialNumber" /></div><div className="space-y-2"><Label htmlFor="asset-cost">Acquisition cost (minor units)</Label><Input id="asset-cost" name="acquisitionMinor" type="number" min="0" required /></div><div className="space-y-2"><Label htmlFor="asset-life">Useful life (months)</Label><Input id="asset-life" name="usefulLifeMonths" type="number" min="1" required /></div><div className="sm:col-span-2 lg:col-span-3 flex items-center justify-between gap-3"><Message value={message} /><Button>Register asset</Button></div></form>;
}

export function AssetStatusButton({ id, toStatus }: { id: string; toStatus: "retired" | "disposed" | "active" }) {
  const [message, setMessage] = useState("");
  async function submit() { const result = await transitionAssetAction({ id, toStatus }); if (!result.ok) { setMessage(result.error); throw new Error(result.error); } setMessage(result.message ?? "Updated."); window.location.reload(); }
  return <div className="flex items-center gap-2"><ConfirmDialog label={toStatus} title={`Mark this asset ${toStatus}?`} description={toStatus === "disposed" ? "The asset will be marked disposed and removed from active asset operations. This status is retained in the asset history." : "The asset lifecycle status will be changed and retained in the asset history."} triggerVariant="outline" confirmVariant={toStatus === "active" ? "default" : "destructive"} onConfirm={submit} /><Message value={message} /></div>;
}

export function AssetAssignmentForm({ assets, students, employees }: { assets: Asset[]; students: Assignee[]; employees: Assignee[] }) {
  const [message, setMessage] = useState("");
  const [assigneeType, setAssigneeType] = useState<"student" | "employee">("student");
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); const result = await assignAssetAction({ assetId: data.get("assetId"), assigneeType: data.get("assigneeType"), assigneeId: data.get("assigneeId"), notes: data.get("notes") }); setMessage(result.ok ? result.message ?? "Assigned." : result.error); if (result.ok) event.currentTarget.reset(); }
  const options = (type: "student" | "employee") => type === "student" ? students.map((person) => <option key={person.id} value={person.id}>{person.admissionNumber ?? person.id} · {person.firstName} {person.lastName}</option>) : employees.map((person) => <option key={person.id} value={person.id}>{person.employeeNumber ?? person.id} · {person.firstName} {person.lastName}</option>);
  return <form onSubmit={submit} className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4" noValidate><div className="space-y-2"><Label htmlFor="assignment-asset">Asset</Label><select id="assignment-asset" name="assetId" className="h-10 w-full rounded-md border bg-background px-3 text-sm" required><option value="">Choose an asset</option>{assets.map((asset) => <option key={asset.id} value={asset.id}>{asset.code ?? asset.id} · {asset.name}</option>)}</select></div><div className="space-y-2"><Label htmlFor="assignment-type">Assignee type</Label><select id="assignment-type" name="assigneeType" className="h-10 w-full rounded-md border bg-background px-3 text-sm" value={assigneeType} onChange={(event) => setAssigneeType(event.target.value as "student" | "employee")}><option value="student">Student</option><option value="employee">Employee</option></select></div><div className="space-y-2"><Label htmlFor="assignment-person">Assignee</Label><select id="assignment-person" name="assigneeId" className="h-10 w-full rounded-md border bg-background px-3 text-sm" required><option value="">Choose an assignee</option>{options(assigneeType)}</select></div><div className="space-y-2"><Label htmlFor="assignment-notes">Notes</Label><Input id="assignment-notes" name="notes" /></div><div className="sm:col-span-2 lg:col-span-4 flex items-center justify-between gap-3"><Message value={message} /><Button disabled={!assets.length || (assigneeType === "student" ? !students.length : !employees.length)}>Assign asset</Button></div></form>;
}

export function AssetAssignmentStatusButton({ id, toStatus }: { id: string; toStatus: "returned" | "cancelled" }) { const [message, setMessage] = useState(""); async function submit() { const result = await transitionAssetAssignmentAction({ id, toStatus }); if (!result.ok) { setMessage(result.error); throw new Error(result.error); } setMessage(result.message ?? "Updated."); window.location.reload(); } return <div className="flex items-center gap-2"><ConfirmDialog label={toStatus} title={`Mark assignment ${toStatus}?`} description="The assignment status will be changed. Confirm that the asset is returned or the assignment is being cancelled before continuing." triggerVariant="outline" confirmVariant={toStatus === "cancelled" ? "destructive" : "default"} onConfirm={submit} /><Message value={message} /></div>; }

export function AssetMaintenanceForm({ assets }: { assets: Asset[] }) { const [message, setMessage] = useState(""); async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); const result = await createAssetMaintenanceAction({ assetId: data.get("assetId"), title: data.get("title"), costMinor: data.get("costMinor"), notes: data.get("notes") }); setMessage(result.ok ? result.message ?? "Created." : result.error); if (result.ok) event.currentTarget.reset(); } return <form onSubmit={submit} className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4" noValidate><div className="space-y-2"><Label htmlFor="maintenance-asset">Asset</Label><select id="maintenance-asset" name="assetId" className="h-10 w-full rounded-md border bg-background px-3 text-sm" required><option value="">Choose an asset</option>{assets.map((asset) => <option key={asset.id} value={asset.id}>{asset.code ?? asset.id} · {asset.name}</option>)}</select></div><div className="space-y-2"><Label htmlFor="maintenance-title">Work description</Label><Input id="maintenance-title" name="title" required /></div><div className="space-y-2"><Label htmlFor="maintenance-cost">Estimated cost (minor units)</Label><Input id="maintenance-cost" name="costMinor" type="number" min="0" required /></div><div className="space-y-2"><Label htmlFor="maintenance-notes">Notes</Label><Input id="maintenance-notes" name="notes" /></div><div className="sm:col-span-2 lg:col-span-4 flex items-center justify-between gap-3"><Message value={message} /><Button disabled={!assets.length}>Create maintenance ticket</Button></div></form>; }

export function AssetMaintenanceStatusButton({ id, toStatus }: { id: string; toStatus: "in_progress" | "completed" | "cancelled" }) { const [message, setMessage] = useState(""); async function submit() { const result = await transitionAssetMaintenanceAction({ id, toStatus }); if (!result.ok) { setMessage(result.error); throw new Error(result.error); } setMessage(result.message ?? "Updated."); window.location.reload(); } return <div className="flex items-center gap-2"><ConfirmDialog label={toStatus.replaceAll("_", " ")} title={`Mark maintenance ${toStatus.replaceAll("_", " ")}?`} description="The maintenance workflow status will be changed and retained in the maintenance history." triggerVariant="outline" confirmVariant={toStatus === "cancelled" ? "destructive" : "default"} onConfirm={submit} /><Message value={message} /></div>; }

export function AssetDepreciationForm({ assets }: { assets: Asset[] }) { const [message, setMessage] = useState(""); async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); const result = await postAssetDepreciationAction({ assetId: data.get("assetId"), period: data.get("period"), amountMinor: data.get("amountMinor") }); setMessage(result.ok ? result.message ?? "Posted." : result.error); if (result.ok) event.currentTarget.reset(); } return <form onSubmit={submit} className="grid gap-4 sm:grid-cols-3" noValidate><div className="space-y-2"><Label htmlFor="depreciation-asset">Asset</Label><select id="depreciation-asset" name="assetId" className="h-10 w-full rounded-md border bg-background px-3 text-sm" required><option value="">Choose an asset</option>{assets.map((asset) => <option key={asset.id} value={asset.id}>{asset.code ?? asset.id} · {asset.name} · book {details(asset.detailsJson).bookValueMinor ?? 0}</option>)}</select></div><div className="space-y-2"><Label htmlFor="depreciation-period">Period</Label><Input id="depreciation-period" name="period" type="month" required /></div><div className="space-y-2"><Label htmlFor="depreciation-amount">Amount (minor units)</Label><Input id="depreciation-amount" name="amountMinor" type="number" min="1" required /></div><div className="sm:col-span-3 flex items-center justify-between gap-3"><Message value={message} /><Button disabled={!assets.length}>Post depreciation</Button></div></form>; }
