import { PageHeader } from "@/components/common/page-header";
import { EmptyState } from "@/components/common/empty-state";
import { StatusBadge } from "@/components/common/status-badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { GatePassButton, GatePassForm } from "@/features/safety/components/safety-workspace";
import { listGatePasses, listVisitors } from "@/lib/api-client/server-queries";
import { requirePermission } from "@/lib/auth/guards";
import { hasPermission } from "@/lib/rbac/permissions";

export default async function SafetyGatePassesPage() { const user = await requirePermission("safety:read"); const [passes, visitors] = await Promise.all([listGatePasses(user), listVisitors(user)]); return <div className="space-y-6"><PageHeader title="Gate passes" description="Issue time-bounded visitor access only after a scoped request is approved." />{hasPermission(user, "safety:create") ? <Card><CardHeader><CardTitle>Request gate pass</CardTitle></CardHeader><CardContent><GatePassForm visitors={visitors.filter((visitor) => visitor.status === "expected")} /></CardContent></Card> : null}<Card><CardHeader><CardTitle>Pass history</CardTitle></CardHeader><CardContent>{passes.length ? <div className="space-y-3">{passes.map((pass) => <div key={pass.id} className="flex flex-wrap items-center justify-between gap-3 rounded-lg border p-4"><div><p className="font-medium">{pass.name}</p><p className="text-xs text-muted-foreground">Visitor {pass.referenceId ?? "unknown"} · valid until {pass.effectiveAt ? new Date(pass.effectiveAt).toLocaleString() : "unknown"}</p></div><div className="flex items-center gap-3"><StatusBadge status={pass.status} />{hasPermission(user, "safety:approve") && pass.status === "requested" ? <><GatePassButton id={pass.id} toStatus="approved" /><GatePassButton id={pass.id} toStatus="rejected" /></> : null}{hasPermission(user, "safety:update") && pass.status === "approved" ? <GatePassButton id={pass.id} toStatus="used" /> : null}</div></div>)}</div> : <EmptyState title="No gate passes found" description="Request a gate pass above when a visitor needs approved access." />}</CardContent></Card></div>; }
