import { PageHeader } from "@/components/common/page-header";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { FacilityComplaintButton, FacilityComplaintForm } from "@/features/facilities/components/facilities-workspace";
import { listFacilityComplaints } from "@/features/facilities/services/facilities.service";
import { requirePermission } from "@/lib/auth/guards";
import { hasPermission } from "@/lib/rbac/permissions";

function details(value: string | null) { try { return value ? JSON.parse(value) as { facilityName?: string } : {}; } catch { return {}; } }
export default async function FacilitiesComplaintsPage() { const user = await requirePermission("facilities:read"); const complaints = await listFacilityComplaints(user); return <div className="space-y-6"><PageHeader title="Facility complaints" description="Submit and resolve facility complaints with a tenant-scoped status trail." />{hasPermission(user, "facilities:create") ? <Card><CardHeader><CardTitle>Submit complaint</CardTitle></CardHeader><CardContent><FacilityComplaintForm /></CardContent></Card> : null}<Card><CardHeader><CardTitle>Complaint history</CardTitle></CardHeader><CardContent>{complaints.length ? <div className="space-y-3">{complaints.map((complaint) => { const info = details(complaint.detailsJson); return <div key={complaint.id} className="flex flex-wrap items-center justify-between gap-3 rounded-lg border p-4"><div><p className="font-medium">{complaint.name}</p><p className="text-xs text-muted-foreground">{info.facilityName ?? "Facility"}</p></div><div className="flex items-center gap-3"><Badge variant={complaint.status === "resolved" || complaint.status === "closed" ? "success" : "secondary"}>{complaint.status}</Badge>{hasPermission(user, "facilities:update") && complaint.status === "open" ? <FacilityComplaintButton id={complaint.id} toStatus="in_progress" /> : null}{hasPermission(user, "facilities:update") && complaint.status === "in_progress" ? <FacilityComplaintButton id={complaint.id} toStatus="resolved" /> : null}{hasPermission(user, "facilities:update") && complaint.status === "resolved" ? <FacilityComplaintButton id={complaint.id} toStatus="closed" /> : null}</div></div>; })}</div> : <p className="rounded-lg border border-dashed p-8 text-center text-sm text-muted-foreground">No complaints found.</p>}</CardContent></Card></div>; }
