"use client";

import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { createFacilityBookingAction, createFacilityComplaintAction, createFacilityMaintenanceAction, transitionFacilityBookingAction, transitionFacilityComplaintAction, transitionFacilityMaintenanceAction } from "../actions/facilities.actions";

function Message({ value }: { value: string }) { return value ? <p role="status" className="text-sm text-muted-foreground">{value}</p> : null; }
export function FacilityBookingForm() { const [message, setMessage] = useState(""); async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); const result = await createFacilityBookingAction({ facilityName: data.get("facilityName"), purpose: data.get("purpose"), startsAt: data.get("startsAt"), endsAt: data.get("endsAt") }); setMessage(result.ok ? result.message ?? "Requested." : result.error); if (result.ok) event.currentTarget.reset(); } return <form onSubmit={submit} className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4" noValidate><div className="space-y-2"><Label htmlFor="booking-facility">Facility</Label><Input id="booking-facility" name="facilityName" required /></div><div className="space-y-2"><Label htmlFor="booking-purpose">Purpose</Label><Input id="booking-purpose" name="purpose" required /></div><div className="space-y-2"><Label htmlFor="booking-start">Starts at</Label><Input id="booking-start" name="startsAt" type="datetime-local" required /></div><div className="space-y-2"><Label htmlFor="booking-end">Ends at</Label><Input id="booking-end" name="endsAt" type="datetime-local" required /></div><div className="sm:col-span-2 lg:col-span-4 flex items-center justify-between gap-3"><Message value={message} /><Button>Request booking</Button></div></form>; }
export function FacilityBookingButton({ id, toStatus }: { id: string; toStatus: "approved" | "rejected" | "cancelled" | "completed" }) { const [message, setMessage] = useState(""); async function submit() { const result = await transitionFacilityBookingAction({ id, toStatus }); setMessage(result.ok ? result.message ?? "Updated." : result.error); if (result.ok) window.location.reload(); } return <div className="flex items-center gap-2"><Button size="sm" variant="outline" onClick={submit}>{toStatus}</Button><Message value={message} /></div>; }
export function FacilityMaintenanceForm() { const [message, setMessage] = useState(""); async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); const result = await createFacilityMaintenanceAction({ facilityName: data.get("facilityName"), title: data.get("title"), priority: data.get("priority"), details: data.get("details") }); setMessage(result.ok ? result.message ?? "Created." : result.error); if (result.ok) event.currentTarget.reset(); } return <form onSubmit={submit} className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4" noValidate><div className="space-y-2"><Label htmlFor="facility-maintenance-name">Facility</Label><Input id="facility-maintenance-name" name="facilityName" required /></div><div className="space-y-2"><Label htmlFor="facility-maintenance-title">Issue</Label><Input id="facility-maintenance-title" name="title" required /></div><div className="space-y-2"><Label htmlFor="facility-maintenance-priority">Priority</Label><select id="facility-maintenance-priority" name="priority" className="h-10 w-full rounded-md border bg-background px-3 text-sm"><option>low</option><option>medium</option><option>high</option><option>critical</option></select></div><div className="space-y-2"><Label htmlFor="facility-maintenance-details">Details</Label><Input id="facility-maintenance-details" name="details" required /></div><div className="sm:col-span-2 lg:col-span-4 flex items-center justify-between gap-3"><Message value={message} /><Button>Create ticket</Button></div></form>; }
export function FacilityMaintenanceButton({ id, toStatus }: { id: string; toStatus: "in_progress" | "completed" | "cancelled" }) { const [message, setMessage] = useState(""); async function submit() { const result = await transitionFacilityMaintenanceAction({ id, toStatus }); setMessage(result.ok ? result.message ?? "Updated." : result.error); if (result.ok) window.location.reload(); } return <div className="flex items-center gap-2"><Button size="sm" variant="outline" onClick={submit}>{toStatus.replaceAll("_", " ")}</Button><Message value={message} /></div>; }
export function FacilityComplaintForm() { const [message, setMessage] = useState(""); async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); const result = await createFacilityComplaintAction({ facilityName: data.get("facilityName"), title: data.get("title"), details: data.get("details") }); setMessage(result.ok ? result.message ?? "Submitted." : result.error); if (result.ok) event.currentTarget.reset(); } return <form onSubmit={submit} className="grid gap-4 sm:grid-cols-3" noValidate><div className="space-y-2"><Label htmlFor="complaint-facility">Facility</Label><Input id="complaint-facility" name="facilityName" required /></div><div className="space-y-2"><Label htmlFor="complaint-title">Complaint</Label><Input id="complaint-title" name="title" required /></div><div className="space-y-2"><Label htmlFor="complaint-details">Details</Label><Input id="complaint-details" name="details" required /></div><div className="sm:col-span-3 flex items-center justify-between gap-3"><Message value={message} /><Button>Submit complaint</Button></div></form>; }
export function FacilityComplaintButton({ id, toStatus }: { id: string; toStatus: "in_progress" | "resolved" | "closed" | "rejected" }) { const [message, setMessage] = useState(""); async function submit() { const result = await transitionFacilityComplaintAction({ id, toStatus }); setMessage(result.ok ? result.message ?? "Updated." : result.error); if (result.ok) window.location.reload(); } return <div className="flex items-center gap-2"><Button size="sm" variant="outline" onClick={submit}>{toStatus}</Button><Message value={message} /></div>; }
