"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { createQuestionBankItemAction, generateReportCardAction } from "../actions/deep-feature.actions";

type Option = { id: string; name: string };
type Question = { id: string; prompt: string; questionType: string; maximumMarks: number; subjectId: string; subjectName: string | null };
type ReportCard = { id: string; exam: string; student: string; percentage: number | null; total: number | null; maximum: number | null; generatedAt: Date; status: string };

export function QuestionBankWorkspace({ subjects, rows, canCreate }: { subjects: Option[]; rows: Question[]; canCreate: boolean }) { const router = useRouter(); const [message, setMessage] = useState(""); async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const result = await createQuestionBankItemAction(Object.fromEntries(new FormData(event.currentTarget).entries())); setMessage(result.ok ? result.message ?? "Saved." : result.error); if (result.ok) { event.currentTarget.reset(); router.refresh(); } } return <div className="space-y-6">{canCreate ? <Card><CardHeader><CardTitle>Add question</CardTitle></CardHeader><CardContent><form className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4" onSubmit={submit}><div><Label>Subject</Label><select className="h-10 w-full rounded-md border bg-background px-3 text-sm" name="subjectId" required>{subjects.map((subject) => <option key={subject.id} value={subject.id}>{subject.name}</option>)}</select></div><div><Label>Type</Label><select className="h-10 w-full rounded-md border bg-background px-3 text-sm" name="questionType"><option value="mcq">MCQ</option><option value="short_answer">Short answer</option><option value="long_answer">Long answer</option><option value="true_false">True/false</option></select></div><div><Label>Maximum marks</Label><Input name="maximumMarks" type="number" min="1" required /></div><div className="sm:col-span-2 lg:col-span-4"><Label>Prompt</Label><Input name="prompt" required /></div><div className="sm:col-span-2 lg:col-span-4"><Label>Answer/key (optional)</Label><Input name="answer" /></div><Button>Add question</Button>{message ? <span role="status" className="text-sm text-muted-foreground">{message}</span> : null}</form></CardContent></Card> : null}<Card><CardHeader><CardTitle>Question bank ({rows.length})</CardTitle></CardHeader><CardContent>{rows.length ? <div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b text-left"><th className="p-3">Prompt</th><th className="p-3">Subject</th><th className="p-3">Type</th><th className="p-3">Marks</th></tr></thead><tbody>{rows.map((row) => <tr className="border-b last:border-0" key={row.id}><td className="p-3">{row.prompt}</td><td className="p-3">{row.subjectName ?? row.subjectId}</td><td className="p-3">{row.questionType}</td><td className="p-3">{row.maximumMarks}</td></tr>)}</tbody></table></div> : <p className="rounded-lg border border-dashed p-8 text-center text-sm text-muted-foreground">No questions found.</p>}</CardContent></Card></div>; }

export function ReportCardsWorkspace({ exams, students, rows, canCreate }: { exams: Option[]; students: Option[]; rows: ReportCard[]; canCreate: boolean }) { const router = useRouter(); const [message, setMessage] = useState(""); async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const result = await generateReportCardAction(Object.fromEntries(new FormData(event.currentTarget).entries())); setMessage(result.ok ? result.message ?? "Generated." : result.error); if (result.ok) router.refresh(); } return <div className="space-y-6">{canCreate ? <Card><CardHeader><CardTitle>Generate report card</CardTitle></CardHeader><CardContent><form className="grid gap-3 sm:grid-cols-3" onSubmit={submit}><div><Label>Approved exam</Label><select className="h-10 w-full rounded-md border bg-background px-3 text-sm" name="examId" required>{exams.map((exam) => <option key={exam.id} value={exam.id}>{exam.name}</option>)}</select></div><div><Label>Student</Label><select className="h-10 w-full rounded-md border bg-background px-3 text-sm" name="studentId" required>{students.map((student) => <option key={student.id} value={student.id}>{student.name}</option>)}</select></div><div className="flex items-end gap-3"><Button>Generate</Button>{message ? <span role="status" className="text-sm text-muted-foreground">{message}</span> : null}</div></form></CardContent></Card> : null}<Card><CardHeader><CardTitle>Generated report cards ({rows.length})</CardTitle></CardHeader><CardContent>{rows.length ? <div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b text-left"><th className="p-3">Exam</th><th className="p-3">Student</th><th className="p-3">Score</th><th className="p-3">Generated</th></tr></thead><tbody>{rows.map((row) => <tr className="border-b last:border-0" key={row.id}><td className="p-3">{row.exam}</td><td className="p-3">{row.student}</td><td className="p-3">{row.total ?? "—"}/{row.maximum ?? "—"} ({row.percentage ?? "—"}%)</td><td className="p-3">{row.generatedAt.toLocaleString()}</td></tr>)}</tbody></table></div> : <p className="rounded-lg border border-dashed p-8 text-center text-sm text-muted-foreground">No report cards generated.</p>}</CardContent></Card></div>; }
