"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { createNoticeAction, transitionNoticeAction } from "../actions/notice.actions";
type Row = { id: string; title: string; body: string; audience: string; status: string };
export function NoticeWorkspace({ rows, canCreate, canUpdate }: { rows: Row[]; canCreate: boolean; canUpdate: boolean }) { const router = useRouter(); const [message, setMessage] = useState(""); async function create(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const result = await createNoticeAction(Object.fromEntries(new FormData(event.currentTarget).entries())); setMessage(result.ok ? result.message ?? "Saved." : result.error); if (result.ok) { event.currentTarget.reset(); router.refresh(); } } async function transition(id: string, status: "published" | "archived") { const result = await transitionNoticeAction({ id, status }); setMessage(result.ok ? result.message ?? "Updated." : result.error); if (result.ok) router.refresh(); } return <div className="space-y-6">{canCreate ? <form className="space-y-3 rounded-lg border p-4" onSubmit={create}><div className="grid gap-3 sm:grid-cols-3"><div><Label>Title</Label><Input name="title" required /></div><div><Label>Audience</Label><select className="h-10 w-full rounded-md border bg-background px-3 text-sm" name="audience"><option value="all">Everyone</option><option value="students">Students</option><option value="parents">Parents</option><option value="teachers">Teachers</option><option value="staff">Staff</option></select></div></div><div><Label>Body</Label><Textarea name="body" required /></div><Button>Save draft</Button>{message ? <span className="ml-3 text-sm text-muted-foreground" role="status">{message}</span> : null}</form> : null}<div className="space-y-3">{rows.length ? rows.map((row) => <article className="rounded-lg border p-4" key={row.id}><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-medium">{row.title}</h2><p className="text-xs text-muted-foreground">Audience: {row.audience} · {row.status}</p></div><div className="flex gap-2">{canUpdate && row.status === "draft" ? <Button size="sm" onClick={() => transition(row.id, "published")}>Publish</Button> : null}{canUpdate && row.status !== "archived" ? <Button size="sm" variant="outline" onClick={() => transition(row.id, "archived")}>Archive</Button> : null}</div></div><p className="mt-3 whitespace-pre-wrap text-sm text-muted-foreground">{row.body}</p></article>) : <p className="rounded-lg border border-dashed p-8 text-center text-sm text-muted-foreground">No notices found.</p>}</div></div>; }
