import { PageHeader } from "@/components/common/page-header";
import { StatusBadge } from "@/components/common/status-badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { FacilityBookingButton, FacilityBookingForm } from "@/features/facilities/components/facilities-workspace";
import { listFacilityBookings } from "@/lib/api-client/server-queries";
import { requirePermission } from "@/lib/auth/guards";
import { hasPermission } from "@/lib/rbac/permissions";
import { formatIndiaDateTime } from "@/lib/utils/india-time";

function details(value: string | null) { try { return value ? JSON.parse(value) as { purpose?: string; startsAt?: string; endsAt?: string } : {}; } catch { return {}; } }
export default async function FacilitiesBookingsPage() { const user = await requirePermission("facilities:read"); const bookings = await listFacilityBookings(user); return <div className="space-y-6"><PageHeader title="Facility bookings" description="Request shared spaces and prevent approved time-window overlaps for the same facility." />{hasPermission(user, "facilities:create") ? <Card><CardHeader><CardTitle>Request booking</CardTitle></CardHeader><CardContent><FacilityBookingForm /></CardContent></Card> : null}<Card><CardHeader><CardTitle>Booking history</CardTitle></CardHeader><CardContent>{bookings.length ? <div className="space-y-3">{bookings.map((booking) => { const info = details(booking.detailsJson); return <div key={booking.id} className="flex flex-wrap items-center justify-between gap-3 rounded-lg border p-4"><div><p className="font-medium">{booking.name}</p><p className="text-xs text-muted-foreground">{info.startsAt ? formatIndiaDateTime(info.startsAt) : "unknown"} – {info.endsAt ? formatIndiaDateTime(info.endsAt) : "unknown"}</p></div><div className="flex items-center gap-3"><StatusBadge status={booking.status} />{hasPermission(user, "facilities:approve") && booking.status === "requested" ? <><FacilityBookingButton id={booking.id} toStatus="approved" /><FacilityBookingButton id={booking.id} toStatus="rejected" /></> : null}{hasPermission(user, "facilities:update") && booking.status === "approved" ? <FacilityBookingButton id={booking.id} toStatus="completed" /> : null}</div></div>; })}</div> : <p className="rounded-lg border border-dashed p-8 text-center text-sm text-muted-foreground">No bookings found.</p>}</CardContent></Card></div>; }
