import { PageHeader } from "@/components/common/page-header";
import { StatusBadge } from "@/components/common/status-badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { getAttendanceOverview, listLowAttendance } from "@/lib/api-client/server-queries";
import { requirePermission } from "@/lib/auth/guards";

export default async function AttendanceReportsPage() {
  const user = await requirePermission("attendance:read");
  const [overview, lowAttendance] = await Promise.all([getAttendanceOverview(user), listLowAttendance(user)]);
  return <div className="space-y-6">
    <PageHeader title="Attendance reports" description="Leadership can review active-year attendance across the current campus scope; teachers see only the class and section records assigned to them." />
    <div className="grid gap-4 sm:grid-cols-3"><Metric label="Recorded entries" value={overview.total} /><Metric label="Present or late" value={overview.attended} /><Metric label="Attendance rate" value={`${overview.rate}%`} /></div>
    <Card><CardHeader><CardTitle>Attendance state mix</CardTitle><p className="text-sm text-muted-foreground">Calculated from active academic-year records. Present and late count as attended.</p></CardHeader><CardContent>{overview.states.length ? <div className="space-y-3">{overview.states.map((row) => { const percent = overview.total ? Math.round((row.total / overview.total) * 100) : 0; return <div key={row.state}><div className="mb-1 flex justify-between text-sm"><span className="font-medium">{row.state.replaceAll("_", " ")}</span><span className="text-muted-foreground">{row.total} ({percent}%)</span></div><div className="h-2 rounded-full bg-muted" role="progressbar" aria-label={`${row.state} attendance entries`} aria-valuemin={0} aria-valuemax={100} aria-valuenow={percent}><div className="h-full rounded-full bg-primary" style={{ width: `${percent}%` }} /></div></div>; })}</div> : <p className="rounded-lg border border-dashed p-8 text-center text-sm text-muted-foreground">No attendance has been recorded for an active academic year in this scope.</p>}</CardContent></Card>
    <Card><CardHeader><CardTitle>By class and section</CardTitle></CardHeader><CardContent>{overview.groups.length ? <div className="overflow-x-auto"><table className="w-full text-sm"><caption className="sr-only">Attendance by class and section</caption><thead><tr className="border-b text-left"><th scope="col" className="p-3">Class</th><th scope="col" className="p-3">Section</th><th scope="col" className="p-3 text-right">Recorded</th><th scope="col" className="p-3 text-right">Attended</th><th scope="col" className="p-3 text-right">Rate</th></tr></thead><tbody>{overview.groups.map((row) => <tr className="border-b last:border-0" key={row.sectionId}><td className="p-3">{row.className}</td><td className="p-3">{row.sectionName}</td><td className="p-3 text-right">{row.total}</td><td className="p-3 text-right">{row.attended}</td><td className="p-3 text-right"><StatusBadge status={row.rate < 75 ? "low" : "healthy"} /> <span className="ml-1">{row.rate}%</span></td></tr>)}</tbody></table></div> : <p className="text-sm text-muted-foreground">No class-level attendance records are available.</p>}</CardContent></Card>
    <Card><CardHeader><CardTitle>Low attendance ({lowAttendance.length})</CardTitle><p className="text-sm text-muted-foreground">Students below the configured 75% threshold, using active-year records only.</p></CardHeader><CardContent>{lowAttendance.length ? <div className="overflow-x-auto"><table className="w-full text-sm"><caption className="sr-only">Students below attendance threshold</caption><thead><tr className="border-b text-left"><th scope="col" className="p-3">Student</th><th scope="col" className="p-3 text-right">Recorded</th><th scope="col" className="p-3 text-right">Attended</th><th scope="col" className="p-3 text-right">Attendance</th></tr></thead><tbody>{lowAttendance.map((row) => <tr className="border-b last:border-0" key={row.studentId}><td className="p-3">{row.student}</td><td className="p-3 text-right">{row.total}</td><td className="p-3 text-right">{row.attended}</td><td className="p-3 text-right">{row.percentage}%</td></tr>)}</tbody></table></div> : <p className="rounded-lg border border-dashed p-8 text-center text-sm text-muted-foreground">No students are below the threshold in the current scope.</p>}</CardContent></Card>
  </div>;
}

function Metric({ label, value }: { label: string; value: number | string }) {
  return <Card><CardContent className="pt-6"><span className="block text-xs text-muted-foreground">{label}</span><span className="text-2xl font-semibold">{value}</span></CardContent></Card>;
}
