import type { FastifyPluginAsync } from "fastify";
import { z } from "zod";
import { achievementSchema, alumniDonationSchema, alumniEventRegistrationSchema, alumniEventSchema, alumniProfileSchema, clubMembershipSchema, clubSchema, cmsFormSchema, cmsMediaSchema, cmsPageSchema, formSubmissionSchema, jobBoardPostSchema, mentorshipSchema, sportsFixtureSchema, sportsTeamSchema } from "../../../features/community/schemas/community.schema";
import { createAchievement, createAlumniDonation, createAlumniEvent, createAlumniEventRegistration, createAlumniProfile, createClub, createClubMembership, createCmsForm, createCmsMedia, createCmsPage, createFormSubmission, createJobBoardPost, createMentorship, createSportsFixture, createSportsTeam, listAchievements, listAlumniDonations, listAlumniEventRegistrations, listAlumniEvents, listAlumniProfiles, listClubs, listClubMemberships, listCmsForms, listCmsMedia, listCmsPages, listFormSubmissions, listJobBoardPosts, listMentorships, listSportsFixtures, listSportsTeams, transitionCmsForm, transitionCmsMedia, transitionCmsPage } from "../../../features/community/services/community.service";
import { apiKeyCreateSchema, apiKeyStatusSchema, integrationConfigSchema, integrationStatusSchema } from "../../../features/integrations/schemas/integration.schema";
import { createApiKey, listApiKeys, listIntegrationConfigs, listIntegrationLogs, listWebhookEvents, saveIntegrationConfig, setApiKeyStatus, setIntegrationStatus } from "../../../features/integrations/services/integration.service";
import { razorpayConfigurationSchema } from "../../../lib/integrations/razorpay";
import { saveRazorpayConfiguration } from "../../../features/integrations/services/razorpay-config.service";
import { isAllowedUpload } from "../../../lib/cloudinary/policy";
import { verifyCloudinaryAsset } from "../../../lib/cloudinary/server";
import { authenticateApiRequest, requireApiCsrf, requireApiPermission } from "../auth/bearer-auth";
import { apiCreated, apiSuccess, auditCommand, parseApiBody, routeSchema } from "./route-utils";
import { providerDeploymentHealth } from "../../../lib/integrations/selected-providers";
import { AppError } from "../../../lib/errors/app-error";

type IdParams = { id: string };
const authenticated = { preHandler: authenticateApiRequest };
const mutation = { preHandler: [authenticateApiRequest, requireApiCsrf] };
const transitionPathSchema = z.object({ id: z.string().min(1), toStatus: z.string().trim().min(2).max(40) });

export const communityIntegrationsRoutes: FastifyPluginAsync = async (app) => {
  app.get("/activities/clubs", authenticated, async (request) => apiSuccess(request, await listClubs(requireApiPermission(request, "activities:read"))));
  app.get("/activities/achievements", authenticated, async (request) => apiSuccess(request, await listAchievements(requireApiPermission(request, "activities:read"))));
  app.get("/activities/clubs/memberships", authenticated, async (request) => apiSuccess(request, await listClubMemberships(requireApiPermission(request, "activities:read"))));
  app.get("/activities/sports/teams", authenticated, async (request) => apiSuccess(request, await listSportsTeams(requireApiPermission(request, "activities:read"))));
  app.get("/activities/sports/fixtures", authenticated, async (request) => apiSuccess(request, await listSportsFixtures(requireApiPermission(request, "activities:read"))));
  app.post<{ Body: unknown }>("/activities/clubs", { ...mutation, schema: routeSchema("Create an activities club") }, async (request, reply) => { const user = requireApiPermission(request, "activities:create"); const input = parseApiBody(clubSchema, request.body); const row = await createClub(user, input); await auditCommand(user, { action: "create", module: "activities", entityType: "club", entityId: row.id, campusId: row.campusId, after: { name: row.name } }); return apiCreated(reply, request, { id: row.id }); });
  app.post<{ Body: unknown }>("/activities/achievements", { ...mutation, schema: routeSchema("Record a student achievement") }, async (request, reply) => { const user = requireApiPermission(request, "activities:create"); const input = parseApiBody(achievementSchema, request.body); const row = await createAchievement(user, input); await auditCommand(user, { action: "create", module: "activities", entityType: "student_achievement", entityId: row.id, campusId: row.campusId, after: { studentId: row.studentId, title: row.title } }); return apiCreated(reply, request, { id: row.id }); });
  app.post<{ Body: unknown }>("/activities/clubs/memberships", { ...mutation, schema: routeSchema("Add a student to an activities club") }, async (request, reply) => { const user = requireApiPermission(request, "activities:create"); const input = parseApiBody(clubMembershipSchema, request.body); const row = await createClubMembership(user, input); await auditCommand(user, { action: "create", module: "activities", entityType: "club_membership", entityId: row.id, campusId: row.campusId, after: { referenceId: row.referenceId } }); return apiCreated(reply, request, { id: row.id }); });
  app.post<{ Body: unknown }>("/activities/sports/teams", { ...mutation, schema: routeSchema("Create a sports team") }, async (request, reply) => { const user = requireApiPermission(request, "activities:create"); const input = parseApiBody(sportsTeamSchema, request.body); const row = await createSportsTeam(user, input); await auditCommand(user, { action: "create", module: "activities", entityType: "sports_team", entityId: row.id, campusId: row.campusId, after: { name: row.name } }); return apiCreated(reply, request, { id: row.id }); });
  app.post<{ Body: unknown }>("/activities/sports/fixtures", { ...mutation, schema: routeSchema("Schedule a sports fixture") }, async (request, reply) => { const user = requireApiPermission(request, "activities:create"); const input = parseApiBody(sportsFixtureSchema, request.body); const row = await createSportsFixture(user, input); await auditCommand(user, { action: "create", module: "activities", entityType: "sports_fixture", entityId: row.id, campusId: row.campusId, after: { name: row.name } }); return apiCreated(reply, request, { id: row.id }); });

  app.get("/alumni/profiles", authenticated, async (request) => apiSuccess(request, await listAlumniProfiles(requireApiPermission(request, "alumni:read"))));
  app.get("/alumni/events", authenticated, async (request) => {
    const user = requireApiPermission(request, "alumni:read");
    const [events, registrations] = await Promise.all([
      listAlumniEvents(user),
      listAlumniEventRegistrations(user),
    ]);
    return apiSuccess(request, { events, registrations });
  });
  app.get("/alumni/mentorship", authenticated, async (request) => apiSuccess(request, await listMentorships(requireApiPermission(request, "alumni:read"))));
  app.get("/alumni/jobs", authenticated, async (request) => apiSuccess(request, await listJobBoardPosts(requireApiPermission(request, "alumni:read"))));
  app.get("/alumni/donations", authenticated, async (request) => apiSuccess(request, await listAlumniDonations(requireApiPermission(request, "alumni:read"))));
  app.post<{ Body: unknown }>("/alumni/profiles", { ...mutation, schema: routeSchema("Create an alumni profile") }, async (request, reply) => { const user = requireApiPermission(request, "alumni:create"); const input = parseApiBody(alumniProfileSchema, request.body); const row = await createAlumniProfile(user, input); await auditCommand(user, { action: "create", module: "alumni", entityType: "alumni_profile", entityId: row.id, campusId: row.campusId, after: { name: row.name, directoryVisible: row.directoryVisible } }); return apiCreated(reply, request, { id: row.id }); });
  app.post<{ Body: unknown }>("/alumni/events", { ...mutation, schema: routeSchema("Create an alumni event") }, async (request, reply) => { const user = requireApiPermission(request, "alumni:create"); const input = parseApiBody(alumniEventSchema, request.body); const row = await createAlumniEvent(user, input); await auditCommand(user, { action: "create", module: "alumni", entityType: "alumni_event", entityId: row.id, campusId: row.campusId, after: { name: row.name, status: row.status } }); return apiCreated(reply, request, { id: row.id }); });
  app.post<{ Body: unknown }>("/alumni/events/registrations", { ...mutation, schema: routeSchema("Register an alumni event attendee") }, async (request, reply) => { const user = requireApiPermission(request, "alumni:create"); const input = parseApiBody(alumniEventRegistrationSchema, request.body); const row = await createAlumniEventRegistration(user, input); await auditCommand(user, { action: "create", module: "alumni", entityType: "event_registration", entityId: row.id, campusId: row.campusId, after: { referenceId: row.referenceId } }); return apiCreated(reply, request, { id: row.id }); });
  app.post<{ Body: unknown }>("/alumni/mentorship", { ...mutation, schema: routeSchema("Create an alumni mentorship request") }, async (request, reply) => { const user = requireApiPermission(request, "alumni:create"); const input = parseApiBody(mentorshipSchema, request.body); const row = await createMentorship(user, input); await auditCommand(user, { action: "create", module: "alumni", entityType: "mentorship", entityId: row.id, campusId: row.campusId, after: { status: row.status } }); return apiCreated(reply, request, { id: row.id }); });
  app.post<{ Body: unknown }>("/alumni/jobs", { ...mutation, schema: routeSchema("Create an alumni job post") }, async (request, reply) => { const user = requireApiPermission(request, "alumni:create"); const input = parseApiBody(jobBoardPostSchema, request.body); const row = await createJobBoardPost(user, input); await auditCommand(user, { action: "create", module: "alumni", entityType: "job_board_post", entityId: row.id, campusId: row.campusId, after: { name: row.name, status: row.status } }); return apiCreated(reply, request, { id: row.id }); });
  app.post<{ Body: unknown }>("/alumni/donations", { ...mutation, schema: routeSchema("Record an alumni donation") }, async (request, reply) => { const user = requireApiPermission(request, "alumni:create"); const input = parseApiBody(alumniDonationSchema, request.body); const row = await createAlumniDonation(user, input); await auditCommand(user, { action: "create", module: "alumni", entityType: "alumni_donation", entityId: row.id, campusId: row.campusId, after: { name: row.name, status: row.status } }); return apiCreated(reply, request, { id: row.id }); });

  app.get("/cms/pages", authenticated, async (request) => apiSuccess(request, await listCmsPages(requireApiPermission(request, "cms:read"))));
  app.get("/cms/media", authenticated, async (request) => apiSuccess(request, await listCmsMedia(requireApiPermission(request, "cms:read"))));
  app.get("/cms/forms", authenticated, async (request) => apiSuccess(request, await listCmsForms(requireApiPermission(request, "cms:read"))));
  app.get("/cms/submissions", authenticated, async (request) => apiSuccess(request, await listFormSubmissions(requireApiPermission(request, "cms:read"))));
  app.post<{ Body: unknown }>("/cms/pages", { ...mutation, schema: routeSchema("Create a CMS page") }, async (request, reply) => { const user = requireApiPermission(request, "cms:create"); const input = parseApiBody(cmsPageSchema, request.body); const row = await createCmsPage(user, input); await auditCommand(user, { action: "create", module: "cms", entityType: "cms_page", entityId: row.id, campusId: row.campusId, after: { slug: row.slug, status: row.status } }); return apiCreated(reply, request, { id: row.id }); });
  app.patch<{ Params: IdParams; Body: unknown }>("/cms/pages/:id/status", { ...mutation, schema: routeSchema("Transition a CMS page") }, async (request) => { const user = requireApiPermission(request, "cms:publish"); const input = parseApiBody(transitionPathSchema, { ...(request.body as Record<string, unknown>), id: request.params.id }); const row = await transitionCmsPage(user, input.id, input.toStatus); await auditCommand(user, { action: "update", module: "cms", entityType: "cms_page", entityId: row.id, campusId: row.campusId, after: { status: row.status } }); return apiSuccess(request, { id: row.id }); });
  app.post<{ Body: unknown }>("/cms/media", { ...mutation, schema: routeSchema("Register verified CMS media") }, async (request, reply) => { const user = requireApiPermission(request, "cms:create"); const input = parseApiBody(cmsMediaSchema, request.body); const expectedPrefix = `school-erp/${user.organizationId}/cms_media/`; if (!input.publicId.startsWith(expectedPrefix)) throw new AppError("TENANT_SCOPE_ERROR", "The media upload does not belong to this organization.", 403); const resourceType = input.mediaType === "document" ? "raw" : input.mediaType; const asset = await verifyCloudinaryAsset({ publicId: input.publicId, secureUrl: input.secureUrl, resourceType }); if (!isAllowedUpload({ resourceType: asset.resource_type, format: asset.format, bytes: asset.bytes })) throw new AppError("VALIDATION_ERROR", "The verified media type or size is not allowed.", 422); const row = await createCmsMedia(user, { ...input, secureUrl: asset.secure_url, publicId: asset.public_id }); await auditCommand(user, { action: "create", module: "cms", entityType: "cms_media", entityId: row.id, campusId: row.campusId, after: { name: row.name, status: row.status, publicId: asset.public_id } }); return apiCreated(reply, request, { id: row.id }); });
  app.patch<{ Params: IdParams; Body: unknown }>("/cms/media/:id/status", { ...mutation, schema: routeSchema("Transition CMS media") }, async (request) => { const user = requireApiPermission(request, "cms:publish"); const input = parseApiBody(transitionPathSchema, { ...(request.body as Record<string, unknown>), id: request.params.id }); const row = await transitionCmsMedia(user, input.id, input.toStatus); await auditCommand(user, { action: "update", module: "cms", entityType: "cms_media", entityId: row.id, campusId: row.campusId, after: { status: row.status } }); return apiSuccess(request, { id: row.id }); });
  app.post<{ Body: unknown }>("/cms/forms", { ...mutation, schema: routeSchema("Create a CMS form") }, async (request, reply) => { const user = requireApiPermission(request, "cms:create"); const input = parseApiBody(cmsFormSchema, request.body); const row = await createCmsForm(user, input); await auditCommand(user, { action: "create", module: "cms", entityType: "form", entityId: row.id, campusId: row.campusId, after: { name: row.name, status: row.status } }); return apiCreated(reply, request, { id: row.id }); });
  app.patch<{ Params: IdParams; Body: unknown }>("/cms/forms/:id/status", { ...mutation, schema: routeSchema("Transition a CMS form") }, async (request) => { const user = requireApiPermission(request, "cms:publish"); const input = parseApiBody(transitionPathSchema, { ...(request.body as Record<string, unknown>), id: request.params.id }); const row = await transitionCmsForm(user, input.id, input.toStatus); await auditCommand(user, { action: "update", module: "cms", entityType: "form", entityId: row.id, campusId: row.campusId, after: { status: row.status } }); return apiSuccess(request, { id: row.id }); });
  app.post<{ Body: unknown }>("/cms/submissions", { ...mutation, schema: routeSchema("Record a CMS form submission") }, async (request, reply) => { const user = requireApiPermission(request, "cms:create"); const input = parseApiBody(formSubmissionSchema, request.body); const row = await createFormSubmission(user, input); await auditCommand(user, { action: "create", module: "cms", entityType: "form_submission", entityId: row.id, campusId: row.campusId, after: { formId: row.formId, status: row.status } }); return apiCreated(reply, request, { id: row.id }); });

  app.get("/integrations/configs", authenticated, async (request) => apiSuccess(request, await listIntegrationConfigs(requireApiPermission(request, "integrations:read"))));
  app.get("/integrations/logs", authenticated, async (request) => apiSuccess(request, await listIntegrationLogs(requireApiPermission(request, "integrations:read"))));
  app.get("/integrations/webhook-events", authenticated, async (request) => apiSuccess(request, await listWebhookEvents(requireApiPermission(request, "integrations:read"))));
  app.get("/integrations/providers/health", authenticated, async (request) => {
    const user = requireApiPermission(request, "integrations:read");
    const tenantConfigs = await listIntegrationConfigs(user);
    const tenantProviders = new Set(tenantConfigs.filter((config) => config.status === "configured").map((config) => config.provider.toLowerCase().replaceAll("_", "-")));
    return apiSuccess(request, providerDeploymentHealth().map((provider) => {
      const tenantConfigured = tenantProviders.has(provider.provider) ||
        (provider.provider === "twilio" && [...tenantProviders].some((value) => value.startsWith("twilio-")));
      return { ...provider, tenantConfigured, status: provider.configured || tenantConfigured ? "configured" : "not_configured" };
    }));
  });
  app.get("/integrations/api-keys", authenticated, async (request) => apiSuccess(request, await listApiKeys(requireApiPermission(request, "integrations:read"))));
  app.post<{ Body: unknown }>("/integrations/configs", { ...mutation, schema: routeSchema("Save encrypted integration configuration") }, async (request, reply) => { const user = requireApiPermission(request, "integrations:manage"); const input = parseApiBody(integrationConfigSchema, request.body); const row = await saveIntegrationConfig(user, input); await auditCommand(user, { action: "update", module: "integrations", entityType: "integration_config", entityId: row.id, campusId: row.campusId, after: { provider: row.provider, status: row.status } }); return apiCreated(reply, request, { id: row.id }); });
  app.post<{ Body: unknown }>("/integrations/razorpay/config", { ...mutation, schema: routeSchema("Save encrypted Razorpay configuration") }, async (request, reply) => { const user = requireApiPermission(request, "integrations:manage"); const input = parseApiBody(razorpayConfigurationSchema, request.body); const row = await saveRazorpayConfiguration(user, input); await auditCommand(user, { action: "update", module: "integrations", entityType: "integration_config", entityId: row.id, campusId: null, after: { provider: "razorpay", mode: input.keyId.startsWith("rzp_live_") ? "live" : "test", status: row.status } }); return apiCreated(reply, request, { id: row.id }); });
  app.patch<{ Params: IdParams; Body: unknown }>("/integrations/configs/:id/status", { ...mutation, schema: routeSchema("Enable or disable an integration") }, async (request) => { const user = requireApiPermission(request, "integrations:manage"); const input = parseApiBody(integrationStatusSchema, { ...(request.body as Record<string, unknown>), id: request.params.id }); const row = await setIntegrationStatus(user, input.id, input.status); await auditCommand(user, { action: "update", module: "integrations", entityType: "integration_config", entityId: row.id, campusId: user.campusId, after: row }); return apiSuccess(request, { id: row.id }); });
  app.post<{ Body: unknown }>("/integrations/api-keys", { ...mutation, schema: routeSchema("Create an integration API key") }, async (request, reply) => { const user = requireApiPermission(request, "integrations:manage"); const row = await createApiKey(user, parseApiBody(apiKeyCreateSchema, request.body)); await auditCommand(user, { action: "create", module: "integrations", entityType: "api_key", entityId: row.id, campusId: user.campusId, after: { name: row.name, prefix: row.prefix } }); return apiCreated(reply, request, row); });
  app.patch<{ Params: IdParams; Body: unknown }>("/integrations/api-keys/:id/status", { ...mutation, schema: routeSchema("Revoke or activate an integration API key") }, async (request) => { const user = requireApiPermission(request, "integrations:manage"); const input = parseApiBody(apiKeyStatusSchema, { ...(request.body as Record<string, unknown>), id: request.params.id }); const row = await setApiKeyStatus(user, input.id, input.status); await auditCommand(user, { action: "update", module: "integrations", entityType: "api_key", entityId: row.id, campusId: user.campusId, after: row }); return apiSuccess(request, { id: row.id }); });
};
