import type { FastifyPluginAsync } from "fastify";
import { z } from "zod";
import { assetAssignmentSchema, assetAssignmentStatusSchema, assetDepreciationSchema, assetMaintenanceSchema, assetMaintenanceStatusSchema, assetSchema, assetStatusSchema } from "../../../features/assets/schemas/asset.schema";
import { assignAsset, createAsset, createAssetMaintenance, listAllAssets, listAssetAssignments, listAssetDepreciation, listAssetMaintenance, listAssets, postAssetDepreciation, transitionAsset, transitionAssetAssignment, transitionAssetMaintenance } from "../../../features/assets/services/asset.service";
import { inventoryItemSchema, stockMovementSchema, supplierSchema, supplierUpdateSchema } from "../../../features/inventory/schemas/inventory.schema";
import { archiveSupplier, createInventoryItem, createSupplier, listInventoryItems, listStockMovements, listSuppliers, postStockMovement, updateSupplier } from "../../../features/inventory/services/inventory.service";
import { goodsReceiptSchema, purchaseOrderSchema, requisitionSchema, workflowTransitionSchema } from "../../../features/procurement/schemas/procurement.schema";
import { createPurchaseOrder, createRequisition, listGoodsReceipts, listPurchaseOrders, listRequisitions, postGoodsReceipt, transitionPurchaseOrder, transitionRequisition } from "../../../features/procurement/services/procurement.service";
import { facilityBookingSchema, facilityBookingStatusSchema, facilityComplaintSchema, facilityComplaintStatusSchema, facilityMaintenanceSchema, facilityMaintenanceStatusSchema } from "../../../features/facilities/schemas/facilities.schema";
import { createFacilityBooking, createFacilityComplaint, createFacilityMaintenance, listFacilityBookings, listFacilityComplaints, listFacilityMaintenance, transitionFacilityBooking, transitionFacilityComplaint, transitionFacilityMaintenance } from "../../../features/facilities/services/facilities.service";
import { evacuationSchema, evacuationStatusSchema, gatePassSchema, gatePassStatusSchema, securityIncidentSchema, securityIncidentStatusSchema, visitorSchema } from "../../../features/safety/schemas/safety.schema";
import { closeEvacuation, createEvacuation, createGatePass, createSecurityIncident, createVisitor, listEvacuations, listGatePasses, listSecurityIncidents, listVisitors, transitionGatePass, transitionSecurityIncident } from "../../../features/safety/services/safety.service";
import { employeeSchema, payrollRunSchema } from "../../../features/hr/schemas/hr.schema";
import { createEmployee, createPayrollRun, listEmployees, listPayslips, listPayrollRuns, processPayrollRun } from "../../../features/hr/services/hr.service";
import { authenticateApiRequest, requireApiCsrf, requireApiPermission } from "../auth/bearer-auth";
import { apiCreated, apiSuccess, auditCommand, parseApiBody, queryString, routeSchema } from "./route-utils";

type IdParams = { id: string };
const authenticated = { preHandler: authenticateApiRequest };
const mutation = { preHandler: [authenticateApiRequest, requireApiCsrf] };
const idSchema = z.object({ id: z.string().min(1) });
const runIdSchema = z.object({ runId: z.string().min(1) });

export const operationsRoutes: FastifyPluginAsync = async (app) => {
  app.get("/assets", authenticated, async (request) => apiSuccess(request, await listAssets(requireApiPermission(request, "assets:read"))));
  app.get("/assets/all", authenticated, async (request) => apiSuccess(request, await listAllAssets(requireApiPermission(request, "assets:read"))));
  app.get("/assets/assignments", authenticated, async (request) => apiSuccess(request, await listAssetAssignments(requireApiPermission(request, "assets:read"))));
  app.get("/assets/maintenance", authenticated, async (request) => apiSuccess(request, await listAssetMaintenance(requireApiPermission(request, "assets:read"))));
  app.get("/assets/depreciation", authenticated, async (request) => apiSuccess(request, await listAssetDepreciation(requireApiPermission(request, "assets:read"))));
  app.post<{ Body: unknown }>("/assets", { ...mutation, schema: routeSchema("Register an asset") }, async (request, reply) => { const user = requireApiPermission(request, "assets:create"); const input = parseApiBody(assetSchema, request.body); const row = await createAsset(user, input); await auditCommand(user, { action: "create", module: "assets", entityType: "asset", entityId: row.id, campusId: row.campusId, after: { name: row.name, code: row.code, status: row.status } }); return apiCreated(reply, request, { id: row.id }); });
  app.patch<{ Params: IdParams; Body: unknown }>("/assets/:id/status", { ...mutation, schema: routeSchema("Transition an asset") }, async (request) => { const user = requireApiPermission(request, "assets:update"); const row = await transitionAsset(user, parseApiBody(assetStatusSchema, { ...(request.body as Record<string, unknown>), id: request.params.id })); await auditCommand(user, { action: "update", module: "assets", entityType: "asset", entityId: row.id, campusId: row.campusId, after: { status: row.status } }); return apiSuccess(request, { id: row.id }); });
  app.post<{ Body: unknown }>("/assets/assignments", { ...mutation, schema: routeSchema("Assign an asset") }, async (request, reply) => { const user = requireApiPermission(request, "assets:update"); const input = parseApiBody(assetAssignmentSchema, request.body); const row = await assignAsset(user, input); await auditCommand(user, { action: "create", module: "assets", entityType: "asset_assignment", entityId: row.id, campusId: row.campusId, after: { assetId: input.assetId, assigneeType: input.assigneeType, assigneeId: input.assigneeId, status: row.status } }); return apiCreated(reply, request, { id: row.id }); });
  app.patch<{ Params: IdParams; Body: unknown }>("/assets/assignments/:id/status", { ...mutation, schema: routeSchema("Transition an asset assignment") }, async (request) => { const user = requireApiPermission(request, "assets:update"); const row = await transitionAssetAssignment(user, parseApiBody(assetAssignmentStatusSchema, { ...(request.body as Record<string, unknown>), id: request.params.id })); await auditCommand(user, { action: "update", module: "assets", entityType: "asset_assignment", entityId: row.id, campusId: row.campusId, after: { status: row.status } }); return apiSuccess(request, { id: row.id }); });
  app.post<{ Body: unknown }>("/assets/maintenance", { ...mutation, schema: routeSchema("Create asset maintenance") }, async (request, reply) => { const user = requireApiPermission(request, "assets:update"); const input = parseApiBody(assetMaintenanceSchema, request.body); const row = await createAssetMaintenance(user, input); await auditCommand(user, { action: "create", module: "assets", entityType: "asset_maintenance_ticket", entityId: row.id, campusId: row.campusId, after: { assetId: input.assetId, status: row.status } }); return apiCreated(reply, request, { id: row.id }); });
  app.patch<{ Params: IdParams; Body: unknown }>("/assets/maintenance/:id/status", { ...mutation, schema: routeSchema("Transition asset maintenance") }, async (request) => { const user = requireApiPermission(request, "assets:update"); const row = await transitionAssetMaintenance(user, parseApiBody(assetMaintenanceStatusSchema, { ...(request.body as Record<string, unknown>), id: request.params.id })); await auditCommand(user, { action: "update", module: "assets", entityType: "asset_maintenance_ticket", entityId: row.id, campusId: row.campusId, after: { status: row.status } }); return apiSuccess(request, { id: row.id }); });
  app.post<{ Body: unknown }>("/assets/depreciation", { ...mutation, schema: routeSchema("Post asset depreciation") }, async (request) => { const user = requireApiPermission(request, "assets:update"); const input = parseApiBody(assetDepreciationSchema, request.body); const result = await postAssetDepreciation(user, input); await auditCommand(user, { action: "create", module: "assets", entityType: "asset_depreciation", entityId: result.entry.id, campusId: result.entry.campusId, after: input }); return apiSuccess(request, { id: result.entry.id }); });

  app.get("/inventory/suppliers", authenticated, async (request) => apiSuccess(request, await listSuppliers(requireApiPermission(request, "inventory:read"))));
  app.get<{ Querystring: { search?: string } }>("/inventory/items", authenticated, async (request) => apiSuccess(request, await listInventoryItems(requireApiPermission(request, "inventory:read"), queryString(request.query.search))));
  app.get("/inventory/stock-movements", authenticated, async (request) => apiSuccess(request, await listStockMovements(requireApiPermission(request, "inventory:read"))));
  app.post<{ Body: unknown }>("/inventory/suppliers", { ...mutation, schema: routeSchema("Create an inventory supplier") }, async (request, reply) => { const user = requireApiPermission(request, "inventory:create"); const input = parseApiBody(supplierSchema, request.body); const row = await createSupplier(user, input); await auditCommand(user, { action: "create", module: "inventory", entityType: "supplier", entityId: row.id, campusId: row.campusId, after: row }); return apiCreated(reply, request, { id: row.id }); });
  app.patch<{ Params: IdParams; Body: unknown }>("/inventory/suppliers/:id", { ...mutation, schema: routeSchema("Update an inventory supplier") }, async (request) => { const user = requireApiPermission(request, "inventory:update"); const row = await updateSupplier(user, parseApiBody(supplierUpdateSchema, { ...(request.body as Record<string, unknown>), id: request.params.id })); await auditCommand(user, { action: "update", module: "inventory", entityType: "supplier", entityId: row.id, campusId: row.campusId, after: row }); return apiSuccess(request, { id: row.id }); });
  app.post<{ Params: IdParams }>("/inventory/suppliers/:id/archive", mutation, async (request) => { const user = requireApiPermission(request, "inventory:update"); const row = await archiveSupplier(user, parseApiBody(idSchema, { id: request.params.id }).id); await auditCommand(user, { action: "delete", module: "inventory", entityType: "supplier", entityId: row.id, campusId: row.campusId, after: { status: "archived" } }); return apiSuccess(request, { id: row.id }); });
  app.post<{ Body: unknown }>("/inventory/items", { ...mutation, schema: routeSchema("Create an inventory item") }, async (request, reply) => { const user = requireApiPermission(request, "inventory:create"); const input = parseApiBody(inventoryItemSchema, request.body); const row = await createInventoryItem(user, input); await auditCommand(user, { action: "create", module: "inventory", entityType: "inventory_item", entityId: row.id, campusId: row.campusId, after: { name: row.name, sku: row.sku, reorderLevel: row.reorderLevel } }); return apiCreated(reply, request, { id: row.id }); });
  app.post<{ Body: unknown }>("/inventory/stock-movements", { ...mutation, schema: routeSchema("Post an inventory stock movement") }, async (request) => { const user = requireApiPermission(request, "inventory:update"); const input = parseApiBody(stockMovementSchema, request.body); const result = await postStockMovement(user, input); await auditCommand(user, { action: "update", module: "inventory", entityType: "stock_movement", entityId: result.movement.id, campusId: result.movement.campusId, metadata: { direction: input.direction, quantity: input.quantity, inventoryItemId: input.inventoryItemId } }); return apiSuccess(request, { id: result.movement.id, quantity: result.item.quantity }); });

  app.get("/procurement/requisitions", authenticated, async (request) => apiSuccess(request, await listRequisitions(requireApiPermission(request, "procurement:read"))));
  app.get("/procurement/purchase-orders", authenticated, async (request) => apiSuccess(request, await listPurchaseOrders(requireApiPermission(request, "procurement:read"))));
  app.get("/procurement/goods-receipts", authenticated, async (request) => apiSuccess(request, await listGoodsReceipts(requireApiPermission(request, "procurement:read"))));
  app.post<{ Body: unknown }>("/procurement/requisitions", { ...mutation, schema: routeSchema("Create a purchase requisition") }, async (request, reply) => { const user = requireApiPermission(request, "procurement:create"); const input = parseApiBody(requisitionSchema, request.body); const row = await createRequisition(user, input); await auditCommand(user, { action: "create", module: "procurement", entityType: "purchase_requisition", entityId: row.id, campusId: row.campusId, after: { name: row.name, status: row.status } }); return apiCreated(reply, request, { id: row.id }); });
  app.patch<{ Params: IdParams; Body: unknown }>("/procurement/requisitions/:id/status", { ...mutation, schema: routeSchema("Transition a purchase requisition") }, async (request) => { const user = requireApiPermission(request, "procurement:approve"); const input = parseApiBody(workflowTransitionSchema, { ...(request.body as Record<string, unknown>), id: request.params.id }); const row = await transitionRequisition(user, input.id, input.toStatus); await auditCommand(user, { action: "update", module: "procurement", entityType: "purchase_requisition", entityId: row.id, campusId: row.campusId, after: { status: row.status } }); return apiSuccess(request, { id: row.id }); });
  app.post<{ Body: unknown }>("/procurement/purchase-orders", { ...mutation, schema: routeSchema("Create a purchase order") }, async (request, reply) => { const user = requireApiPermission(request, "procurement:create"); const input = parseApiBody(purchaseOrderSchema, request.body); const row = await createPurchaseOrder(user, input); await auditCommand(user, { action: "create", module: "procurement", entityType: "purchase_order", entityId: row.id, campusId: row.campusId, after: { name: row.name, status: row.status, requisitionId: row.referenceId } }); return apiCreated(reply, request, { id: row.id }); });
  app.patch<{ Params: IdParams; Body: unknown }>("/procurement/purchase-orders/:id/status", { ...mutation, schema: routeSchema("Transition a purchase order") }, async (request) => { const user = requireApiPermission(request, "procurement:approve"); const input = parseApiBody(workflowTransitionSchema, { ...(request.body as Record<string, unknown>), id: request.params.id }); const row = await transitionPurchaseOrder(user, input.id, input.toStatus); await auditCommand(user, { action: "update", module: "procurement", entityType: "purchase_order", entityId: row.id, campusId: row.campusId, after: { status: row.status } }); return apiSuccess(request, { id: row.id }); });
  app.post<{ Body: unknown }>("/procurement/goods-receipts", { ...mutation, schema: routeSchema("Post a goods receipt") }, async (request) => { const user = requireApiPermission(request, "procurement:update"); const input = parseApiBody(goodsReceiptSchema, request.body); const result = await postGoodsReceipt(user, input); await auditCommand(user, { action: "update", module: "procurement", entityType: "goods_receipt", entityId: result.receipt.id, campusId: result.receipt.campusId, after: { purchaseOrderId: input.purchaseOrderId, inventoryItemId: input.inventoryItemId, quantity: input.quantity, stockMovementId: result.movement.id } }); return apiSuccess(request, { id: result.receipt.id, quantity: result.item.quantity }); });

  app.get("/facilities/bookings", authenticated, async (request) => apiSuccess(request, await listFacilityBookings(requireApiPermission(request, "facilities:read"))));
  app.get("/facilities/maintenance", authenticated, async (request) => apiSuccess(request, await listFacilityMaintenance(requireApiPermission(request, "facilities:read"))));
  app.get("/facilities/complaints", authenticated, async (request) => apiSuccess(request, await listFacilityComplaints(requireApiPermission(request, "facilities:read"))));
  app.post<{ Body: unknown }>("/facilities/bookings", { ...mutation, schema: routeSchema("Request a facility booking") }, async (request, reply) => { const user = requireApiPermission(request, "facilities:create"); const input = parseApiBody(facilityBookingSchema, request.body); const row = await createFacilityBooking(user, input); await auditCommand(user, { action: "create", module: "facilities", entityType: "facility_booking", entityId: row.id, campusId: row.campusId, after: { status: row.status } }); return apiCreated(reply, request, { id: row.id }); });
  app.patch<{ Params: IdParams; Body: unknown }>("/facilities/bookings/:id/status", { ...mutation, schema: routeSchema("Transition a facility booking") }, async (request) => { const user = requireApiPermission(request, "facilities:approve"); const row = await transitionFacilityBooking(user, parseApiBody(facilityBookingStatusSchema, { ...(request.body as Record<string, unknown>), id: request.params.id })); await auditCommand(user, { action: "update", module: "facilities", entityType: "facility_booking", entityId: row.id, campusId: row.campusId, after: { status: row.status } }); return apiSuccess(request, { id: row.id }); });
  app.post<{ Body: unknown }>("/facilities/maintenance", { ...mutation, schema: routeSchema("Create a facility maintenance ticket") }, async (request, reply) => { const user = requireApiPermission(request, "facilities:create"); const input = parseApiBody(facilityMaintenanceSchema, request.body); const row = await createFacilityMaintenance(user, input); await auditCommand(user, { action: "create", module: "facilities", entityType: "facility_maintenance", entityId: row.id, campusId: row.campusId, after: { status: row.status } }); return apiCreated(reply, request, { id: row.id }); });
  app.patch<{ Params: IdParams; Body: unknown }>("/facilities/maintenance/:id/status", { ...mutation, schema: routeSchema("Transition facility maintenance") }, async (request) => { const user = requireApiPermission(request, "facilities:update"); const row = await transitionFacilityMaintenance(user, parseApiBody(facilityMaintenanceStatusSchema, { ...(request.body as Record<string, unknown>), id: request.params.id })); await auditCommand(user, { action: "update", module: "facilities", entityType: "facility_maintenance", entityId: row.id, campusId: row.campusId, after: { status: row.status } }); return apiSuccess(request, { id: row.id }); });
  app.post<{ Body: unknown }>("/facilities/complaints", { ...mutation, schema: routeSchema("Create a facility complaint") }, async (request, reply) => { const user = requireApiPermission(request, "facilities:create"); const input = parseApiBody(facilityComplaintSchema, request.body); const row = await createFacilityComplaint(user, input); await auditCommand(user, { action: "create", module: "facilities", entityType: "facility_complaint", entityId: row.id, campusId: row.campusId, after: { status: row.status } }); return apiCreated(reply, request, { id: row.id }); });
  app.patch<{ Params: IdParams; Body: unknown }>("/facilities/complaints/:id/status", { ...mutation, schema: routeSchema("Transition a facility complaint") }, async (request) => { const user = requireApiPermission(request, "facilities:update"); const row = await transitionFacilityComplaint(user, parseApiBody(facilityComplaintStatusSchema, { ...(request.body as Record<string, unknown>), id: request.params.id })); await auditCommand(user, { action: "update", module: "facilities", entityType: "facility_complaint", entityId: row.id, campusId: row.campusId, after: { status: row.status } }); return apiSuccess(request, { id: row.id }); });

  app.get("/safety/visitors", authenticated, async (request) => apiSuccess(request, await listVisitors(requireApiPermission(request, "safety:read"))));
  app.get("/safety/gate-passes", authenticated, async (request) => apiSuccess(request, await listGatePasses(requireApiPermission(request, "safety:read"))));
  app.get("/safety/incidents", authenticated, async (request) => apiSuccess(request, await listSecurityIncidents(requireApiPermission(request, "safety:read"))));
  app.get("/safety/evacuation", authenticated, async (request) => apiSuccess(request, await listEvacuations(requireApiPermission(request, "safety:read"))));
  app.post<{ Body: unknown }>("/safety/visitors", { ...mutation, schema: routeSchema("Register a visitor") }, async (request, reply) => { const user = requireApiPermission(request, "safety:create"); const row = await createVisitor(user, parseApiBody(visitorSchema, request.body)); await auditCommand(user, { action: "create", module: "safety", entityType: "visitor_log", entityId: row.id, campusId: row.campusId, after: { status: row.status } }); return apiCreated(reply, request, { id: row.id }); });
  app.post<{ Body: unknown }>("/safety/gate-passes", { ...mutation, schema: routeSchema("Create a gate pass") }, async (request, reply) => { const user = requireApiPermission(request, "safety:create"); const input = parseApiBody(gatePassSchema, request.body); const row = await createGatePass(user, input); await auditCommand(user, { action: "create", module: "safety", entityType: "gate_pass", entityId: row.id, campusId: row.campusId, after: { status: row.status, visitorId: input.visitorId } }); return apiCreated(reply, request, { id: row.id }); });
  app.patch<{ Params: IdParams; Body: unknown }>("/safety/gate-passes/:id/status", { ...mutation, schema: routeSchema("Transition a gate pass") }, async (request) => { const user = requireApiPermission(request, "safety:approve"); const row = await transitionGatePass(user, parseApiBody(gatePassStatusSchema, { ...(request.body as Record<string, unknown>), id: request.params.id })); await auditCommand(user, { action: "update", module: "safety", entityType: "gate_pass", entityId: row.id, campusId: row.campusId, after: { status: row.status } }); return apiSuccess(request, { id: row.id }); });
  app.post<{ Body: unknown }>("/safety/incidents", { ...mutation, schema: routeSchema("Record a security incident") }, async (request, reply) => { const user = requireApiPermission(request, "safety:create"); const row = await createSecurityIncident(user, parseApiBody(securityIncidentSchema, request.body)); await auditCommand(user, { action: "create", module: "safety", entityType: "security_incident", entityId: row.id, campusId: row.campusId, after: { status: row.status } }); return apiCreated(reply, request, { id: row.id }); });
  app.patch<{ Params: IdParams; Body: unknown }>("/safety/incidents/:id/status", { ...mutation, schema: routeSchema("Transition a security incident") }, async (request) => { const user = requireApiPermission(request, "safety:update"); const row = await transitionSecurityIncident(user, parseApiBody(securityIncidentStatusSchema, { ...(request.body as Record<string, unknown>), id: request.params.id })); await auditCommand(user, { action: "update", module: "safety", entityType: "security_incident", entityId: row.id, campusId: row.campusId, after: { status: row.status } }); return apiSuccess(request, { id: row.id }); });
  app.post<{ Body: unknown }>("/safety/evacuation", { ...mutation, schema: routeSchema("Open an evacuation roll call") }, async (request, reply) => { const user = requireApiPermission(request, "safety:create"); const row = await createEvacuation(user, parseApiBody(evacuationSchema, request.body)); await auditCommand(user, { action: "create", module: "safety", entityType: "evacuation_roll_call", entityId: row.id, campusId: row.campusId, after: { status: row.status } }); return apiCreated(reply, request, { id: row.id }); });
  app.patch<{ Params: IdParams; Body: unknown }>("/safety/evacuation/:id/status", { ...mutation, schema: routeSchema("Close an evacuation roll call") }, async (request) => { const user = requireApiPermission(request, "safety:update"); const row = await closeEvacuation(user, parseApiBody(evacuationStatusSchema, { ...(request.body as Record<string, unknown>), id: request.params.id })); await auditCommand(user, { action: "update", module: "safety", entityType: "evacuation_roll_call", entityId: row.id, campusId: row.campusId, after: { status: row.status } }); return apiSuccess(request, { id: row.id }); });

  app.get<{ Querystring: { search?: string } }>("/hr/employees", authenticated, async (request) => apiSuccess(request, await listEmployees(requireApiPermission(request, "hr:read"), queryString(request.query.search))));
  app.get("/payroll/runs", authenticated, async (request) => apiSuccess(request, await listPayrollRuns(requireApiPermission(request, "payroll:read"))));
  app.get("/payroll/payslips", authenticated, async (request) => apiSuccess(request, await listPayslips(requireApiPermission(request, "payroll:read"))));
  app.post<{ Body: unknown }>("/hr/employees", { ...mutation, schema: routeSchema("Create an employee") }, async (request, reply) => { const user = requireApiPermission(request, "hr:create"); const row = await createEmployee(user, parseApiBody(employeeSchema, request.body)); await auditCommand(user, { action: "create", module: "hr", entityType: "employee", entityId: row.id, campusId: row.campusId, after: { employeeNumber: row.employeeNumber, name: `${row.firstName} ${row.lastName}` } }); return apiCreated(reply, request, { id: row.id }); });
  app.post<{ Body: unknown }>("/payroll/runs", { ...mutation, schema: routeSchema("Create a payroll run") }, async (request, reply) => { const user = requireApiPermission(request, "payroll:create"); const row = await createPayrollRun(user, parseApiBody(payrollRunSchema, request.body)); await auditCommand(user, { action: "create", module: "payroll", entityType: "payroll_run", entityId: row.id, campusId: row.campusId, after: { period: row.period, status: row.status } }); return apiCreated(reply, request, { id: row.id }); });
  app.post<{ Params: IdParams }>("/payroll/runs/:id/process", mutation, async (request) => { const user = requireApiPermission(request, "payroll:update"); const result = await processPayrollRun(user, parseApiBody(runIdSchema, { runId: request.params.id }).runId); await auditCommand(user, { action: "update", module: "payroll", entityType: "payroll_run", entityId: result.run.id, campusId: result.run.campusId, after: { status: result.run.status, payslipCount: result.payslipCount, totalMinor: result.totalMinor } }); return apiSuccess(request, { id: result.run.id, payslipCount: result.payslipCount, totalMinor: result.totalMinor }); });
};
