"use server";

import { revalidatePath } from "next/cache";
import { requirePermission } from "@/lib/auth/guards";
import { writeAuditLog } from "@/lib/audit/audit-log";
import type { ActionResult } from "@/lib/errors/result";
import { closeEvacuation, createEvacuation, createGatePass, createSecurityIncident, createVisitor, transitionGatePass, transitionSecurityIncident } from "../services/safety.service";
import { evacuationSchema, evacuationStatusSchema, gatePassSchema, gatePassStatusSchema, securityIncidentSchema, securityIncidentStatusSchema, visitorSchema } from "../schemas/safety.schema";

function invalid(message: string): ActionResult<{ id: string }> { return { ok: false, error: message, code: "VALIDATION_ERROR" }; }

export async function createVisitorAction(input: unknown): Promise<ActionResult<{ id: string }>> { const parsed = visitorSchema.safeParse(input); if (!parsed.success) return invalid(parsed.error.issues[0]?.message ?? "Visitor details are invalid."); try { const user = await requirePermission("safety:create"); const row = await createVisitor(user, parsed.data); await writeAuditLog(user, { action: "create", module: "safety", entityType: "visitor_log", entityId: row.id, campusId: row.campusId, after: { status: row.status } }); revalidatePath("/safety/visitors"); revalidatePath("/safety/gate-passes"); return { ok: true, data: { id: row.id }, message: "Visitor registered." }; } catch (error) { return { ok: false, error: error instanceof Error ? error.message : "Unable to register visitor." }; } }
export async function createGatePassAction(input: unknown): Promise<ActionResult<{ id: string }>> { const parsed = gatePassSchema.safeParse(input); if (!parsed.success) return invalid(parsed.error.issues[0]?.message ?? "Gate pass details are invalid."); try { const user = await requirePermission("safety:create"); const row = await createGatePass(user, parsed.data); await writeAuditLog(user, { action: "create", module: "safety", entityType: "gate_pass", entityId: row.id, campusId: row.campusId, after: { status: row.status, visitorId: parsed.data.visitorId } }); revalidatePath("/safety/gate-passes"); return { ok: true, data: { id: row.id }, message: "Gate pass requested." }; } catch (error) { return { ok: false, error: error instanceof Error ? error.message : "Unable to create gate pass." }; } }
export async function transitionGatePassAction(input: unknown): Promise<ActionResult<{ id: string }>> { const parsed = gatePassStatusSchema.safeParse(input); if (!parsed.success) return invalid(parsed.error.issues[0]?.message ?? "Gate pass status is invalid."); try { const user = await requirePermission("safety:approve"); const row = await transitionGatePass(user, parsed.data); await writeAuditLog(user, { action: "update", module: "safety", entityType: "gate_pass", entityId: row.id, campusId: row.campusId, after: { status: row.status } }); revalidatePath("/safety/gate-passes"); return { ok: true, data: { id: row.id }, message: `Gate pass moved to ${row.status}.` }; } catch (error) { return { ok: false, error: error instanceof Error ? error.message : "Unable to update gate pass." }; } }
export async function createSecurityIncidentAction(input: unknown): Promise<ActionResult<{ id: string }>> { const parsed = securityIncidentSchema.safeParse(input); if (!parsed.success) return invalid(parsed.error.issues[0]?.message ?? "Incident details are invalid."); try { const user = await requirePermission("safety:create"); const row = await createSecurityIncident(user, parsed.data); await writeAuditLog(user, { action: "create", module: "safety", entityType: "security_incident", entityId: row.id, campusId: row.campusId, after: { status: row.status } }); revalidatePath("/safety/incidents"); return { ok: true, data: { id: row.id }, message: "Security incident recorded." }; } catch (error) { return { ok: false, error: error instanceof Error ? error.message : "Unable to record incident." }; } }
export async function transitionSecurityIncidentAction(input: unknown): Promise<ActionResult<{ id: string }>> { const parsed = securityIncidentStatusSchema.safeParse(input); if (!parsed.success) return invalid(parsed.error.issues[0]?.message ?? "Incident status is invalid."); try { const user = await requirePermission("safety:update"); const row = await transitionSecurityIncident(user, parsed.data); await writeAuditLog(user, { action: "update", module: "safety", entityType: "security_incident", entityId: row.id, campusId: row.campusId, after: { status: row.status } }); revalidatePath("/safety/incidents"); return { ok: true, data: { id: row.id }, message: `Incident moved to ${row.status}.` }; } catch (error) { return { ok: false, error: error instanceof Error ? error.message : "Unable to update incident." }; } }
export async function createEvacuationAction(input: unknown): Promise<ActionResult<{ id: string }>> { const parsed = evacuationSchema.safeParse(input); if (!parsed.success) return invalid(parsed.error.issues[0]?.message ?? "Roll call details are invalid."); try { const user = await requirePermission("safety:create"); const row = await createEvacuation(user, parsed.data); await writeAuditLog(user, { action: "create", module: "safety", entityType: "evacuation_roll_call", entityId: row.id, campusId: row.campusId, after: { status: row.status } }); revalidatePath("/safety/evacuation"); return { ok: true, data: { id: row.id }, message: "Evacuation roll call opened." }; } catch (error) { return { ok: false, error: error instanceof Error ? error.message : "Unable to open roll call." }; } }
export async function closeEvacuationAction(input: unknown): Promise<ActionResult<{ id: string }>> { const parsed = evacuationStatusSchema.safeParse(input); if (!parsed.success) return invalid(parsed.error.issues[0]?.message ?? "Roll call status is invalid."); try { const user = await requirePermission("safety:update"); const row = await closeEvacuation(user, parsed.data); await writeAuditLog(user, { action: "update", module: "safety", entityType: "evacuation_roll_call", entityId: row.id, campusId: row.campusId, after: { status: row.status } }); revalidatePath("/safety/evacuation"); return { ok: true, data: { id: row.id }, message: "Evacuation roll call closed." }; } catch (error) { return { ok: false, error: error instanceof Error ? error.message : "Unable to close roll call." }; } }
